/**
 * @frontier/contracts — nodeGraph.ts
 *
 * The world-3 node table: one row per thing the economy can make.
 *
 * Every price is a **balance price** — what one unit costs where supply and
 * demand meet — not a scarcity price and not a list price. Where the real
 * figure is a range, the row takes the middle and the comment says so. Where a
 * number is not obvious, the comment cites what it was checked against, with
 * 2026 figures.
 *
 * ## The six chains, and where they cross
 *
 * - **Semiconductors** (manufacturing) — silicon feedstock → 300mm logic wafer
 *   → logic and accelerator die, HBM stack, substrate → advanced package → AI
 *   accelerator → AI server rack.
 * - **Batteries** (manufacturing) — lithium, nickel and graphite → cathode,
 *   anode and electrolyte → cell → pack.
 * - **Energy** — gas and uranium → grid power; solar module, wind turbine, SMR
 *   module, storage and substation → grid interconnect → power purchase
 *   agreement and datacentre capacity.
 * - **AI** — curated corpus and preference data → training runs → frontier and
 *   small models → inference API → agent platform, software suite, vertical
 *   applications.
 * - **Robotics** — actuators, sensors and edge compute modules, a battery pack
 *   and a policy model → industrial arm, warehouse AMR, humanoid, drone.
 * - **Logistics** — electric trucks and vans (built from packs, drivetrains and
 *   chips) and warehouse automation cells (built from AMRs and arms) → line
 *   haul, last mile, brokerage, routing and port terminals.
 * - **Consumer** — SoCs, camera modules and display panels → devices and
 *   wearables; inference → marketplaces, media, subscriptions, social.
 *
 * They cross in earnest: robotics buys AI training runs and manufacturing
 * structures, logistics buys robots and packs, consumer buys wafers through its
 * own SoC line and inference through the AI chain, and **every** node above
 * tier 1 with an energy draw buys `res_grid_power`, which is what makes every
 * company in the world an energy customer.
 *
 * ## Compute and energy are capacity, not bill of materials
 *
 * `capacityKind: "compute"` draws ACCELERATORS and `"plant" | "fleet" | "grid"`
 * draw $1,000,000 OF INSTALLED CAPITAL. That is why the AI chain does not carry
 * a `consumes` edge on `sys_ai_accelerator`: a training run does not eat
 * accelerators, it occupies them. `energyMwhPerUnit` is the one implicit
 * `consumes` edge in the table, on `res_grid_power`.
 */

import type { ProductSegment, CapacityKind, TechCapabilityArea } from './company';
import type { Sector } from './sectors';
import { SECTORS } from './sectors';
import {
  EconomicNodeSchema,
  GRID_POWER_NODE_ID,
  nodePriceIndex,
  nodePriceUsd,
  type EconomicNode,
  type NodeMaturity,
  type NodePricedState,
  type NodeSaleKind,
  type NodeTier,
} from './nodes';

/* -------------------------------------------------------------------------- */
/*  Defaults                                                                   */
/* -------------------------------------------------------------------------- */

/** Belief defaults per maturity, so ninety rows do not repeat six numbers each. */
const MATURITY_BELIEF: Readonly<Record<NodeMaturity, { confidence: number; novelty: number; plausibility: number; window: readonly [number, number] }>> = {
  commodity: { confidence: 0.99, novelty: 0.02, plausibility: 1, window: [2027, 2027] },
  established: { confidence: 0.95, novelty: 0.1, plausibility: 0.98, window: [2027, 2028] },
  emerging: { confidence: 0.72, novelty: 0.36, plausibility: 0.9, window: [2028, 2031] },
  frontier: { confidence: 0.46, novelty: 0.62, plausibility: 0.78, window: [2030, 2035] },
  speculative: { confidence: 0.22, novelty: 0.85, plausibility: 0.54, window: [2034, 2042] },
  discredited: { confidence: 0.08, novelty: 0.7, plausibility: 0.24, window: [2040, 2048] },
};

/** Programme cost defaults per maturity, before the tier factor below. */
const MATURITY_RESEARCH_COST: Readonly<Record<NodeMaturity, readonly [number, number]>> = {
  commodity: [2_000_000, 8_000_000],
  established: [20_000_000, 90_000_000],
  emerging: [120_000_000, 600_000_000],
  frontier: [700_000_000, 4_000_000_000],
  speculative: [2_000_000_000, 12_000_000_000],
  discredited: [1_000_000_000, 6_000_000_000],
};

/** Which capability areas a sector's programmes draw on, when a row says nothing. */
const SECTOR_TALENT: Readonly<Record<Sector, readonly TechCapabilityArea[]>> = {
  ai: ['reasoning', 'training_systems'],
  robotics: ['agents', 'hardware_design'],
  manufacturing: ['hardware_design', 'infrastructure'],
  energy: ['infrastructure', 'efficiency'],
  logistics: ['infrastructure', 'agents'],
  consumer: ['multimodal', 'retrieval'],
};

/** Healthy churn bands per sale kind. A contract churns at renewal, not monthly. */
const SALE_CHURN: Readonly<Record<NodeSaleKind, readonly [number, number]>> = {
  unit: [0.02, 0.07],
  recurring: [0.06, 0.15],
  contract: [0.01, 0.04],
};

/* -------------------------------------------------------------------------- */
/*  Row builder                                                                */
/* -------------------------------------------------------------------------- */

/** `[nodeId, qtyPerUnit, substitutable]` — a consumes edge in its shortest form. */
type ConsumesTuple = readonly [string, number, boolean];

interface NodeDraft {
  readonly id: string;
  readonly label: string;
  readonly blurb: string;
  readonly sector: Sector;
  readonly tier: NodeTier;
  readonly maturity: NodeMaturity;
  readonly unit: string;
  readonly sale: NodeSaleKind;
  readonly price: number;
  /** Quarters before a unit sale is replaced. Required for `sale: "unit"`. */
  readonly life?: number;
  /** Commitment length. Required for `sale: "contract"`. */
  readonly term?: number;
  readonly requires?: readonly string[];
  readonly consumes?: readonly ConsumesTuple[];
  readonly capacity?: CapacityKind;
  readonly draw?: number;
  readonly labour?: number;
  readonly energy?: number;
  readonly support?: number;
  readonly computeIntensity?: number;
  readonly talent?: readonly TechCapabilityArea[];
  readonly dataPb?: number;
  readonly segment?: ProductSegment;
  readonly demand?: number;
  readonly elasticity?: number;
  readonly churn?: readonly [number, number];
  readonly dataYield?: number;
  readonly dataSensitivity?: number;
}

function node(draft: NodeDraft): EconomicNode {
  const belief = MATURITY_BELIEF[draft.maturity];
  const [costLow, costHigh] = MATURITY_RESEARCH_COST[draft.maturity];
  // A deeper node is a dearer programme: the tier factor keeps ninety research
  // ranges consistent without ninety hand-picked pairs.
  const tierFactor = 1 + draft.tier * 0.35;
  const churn = draft.churn ?? SALE_CHURN[draft.sale];
  const researchable = draft.tier >= 2;
  return EconomicNodeSchema.parse({
    id: draft.id,
    label: draft.label,
    blurb: draft.blurb,
    sector: draft.sector,
    tier: draft.tier,
    maturity: draft.maturity,
    unitLabel: draft.unit,
    saleKind: draft.sale,
    lifetimeQuarters: draft.sale === 'unit' ? (draft.life ?? 12) : null,
    contractQuarters: draft.sale === 'contract' ? (draft.term ?? 12) : null,
    basePriceUsd: draft.price,
    requires: draft.requires ?? [],
    consumes: (draft.consumes ?? []).map(([nodeId, qtyPerUnit, substitutable]) => ({ nodeId, qtyPerUnit, substitutable })),
    capacityKind: draft.capacity ?? 'none',
    capacityDrawPerUnit: draft.draw ?? 0,
    labourPerUnit: draft.labour ?? 0,
    energyMwhPerUnit: draft.energy ?? 0,
    supportCostShare: draft.support ?? 0.04,
    researchCostRangeUsd: [Math.round(costLow * tierFactor), Math.round(costHigh * tierFactor)],
    researchComputeIntensity: draft.computeIntensity ?? (draft.sector === 'ai' ? 0.8 : 0.25),
    talentAreas: draft.talent ?? SECTOR_TALENT[draft.sector],
    dataRequiredPb: draft.dataPb ?? 0,
    novelty: belief.novelty,
    plausibility: belief.plausibility,
    researchable,
    publicConfidence: belief.confidence,
    confidenceByCompany: {},
    estimatedWindow: [belief.window[0], belief.window[1]],
    originalProposerId: null,
    visibility: 'public',
    pioneer: null,
    createdQuarter: 0,
    buyerSegment: draft.segment ?? null,
    endDemandBaseUnits: draft.segment === undefined ? 0 : (draft.demand ?? 0),
    elasticity: draft.elasticity ?? 0.8,
    churnBand: { min: churn[0], max: churn[1] },
    dataYieldPerUnitQuarter: draft.dataYield ?? 0,
    dataSensitivity: draft.dataSensitivity ?? 0,
  });
}

/* -------------------------------------------------------------------------- */
/*  Manufacturing — raw materials, semiconductors, batteries, machining        */
/* -------------------------------------------------------------------------- */

const MANUFACTURING_NODES: readonly EconomicNode[] = [
  /* --- tier 0: what comes out of the ground ---------------------------- */
  node({
    id: 'res_silicon_feedstock',
    label: 'Polysilicon',
    blurb: 'Refined silicon feedstock. Everything with a transistor in it starts here.',
    sector: 'manufacturing',
    tier: 0,
    maturity: 'commodity',
    unit: 'kg',
    sale: 'unit',
    life: 1,
    // 2026: China mono premium about $7/kg, Europe about $21, North America
    // about $26. $11 is the middle of the traded range.
    price: 11,
    segment: 'enterprise',
    demand: 420_000_000,
    elasticity: 1.1,
    capacity: 'plant',
    draw: 0.000_02,
    labour: 0.000_002,
  }),
  node({
    id: 'res_lithium_carbonate',
    label: 'Lithium carbonate',
    blurb: 'Battery-grade lithium salt. The metal every cell chemistry is named after.',
    sector: 'manufacturing',
    tier: 0,
    maturity: 'commodity',
    unit: 'tonne',
    sale: 'unit',
    life: 1,
    // 2026 assessments ran $8,800 (South America) to $18,300 (Northeast Asia);
    // $18,000 takes the battery-grade end, which is what a cell maker pays.
    price: 18_000,
    segment: 'enterprise',
    demand: 380_000,
    elasticity: 1.3,
    capacity: 'plant',
    draw: 0.9,
    labour: 0.02,
  }),
  node({
    id: 'res_nickel_sulphate',
    label: 'Nickel sulphate',
    blurb: 'Class-one nickel in the form a cathode plant can actually use.',
    sector: 'manufacturing',
    tier: 0,
    maturity: 'commodity',
    unit: 'tonne',
    sale: 'unit',
    life: 1,
    price: 16_500,
    segment: 'enterprise',
    demand: 260_000,
    elasticity: 1.2,
    capacity: 'plant',
    draw: 0.7,
    labour: 0.015,
  }),
  node({
    id: 'res_graphite',
    label: 'Anode-grade graphite',
    blurb: 'Spherical graphite, natural or synthetic. Half the mass of a cell anode.',
    sector: 'manufacturing',
    tier: 0,
    maturity: 'commodity',
    unit: 'tonne',
    sale: 'unit',
    life: 1,
    price: 6_000,
    segment: 'enterprise',
    demand: 420_000,
    elasticity: 1.1,
    capacity: 'plant',
    draw: 0.5,
    labour: 0.02,
  }),
  node({
    id: 'res_copper_cathode',
    label: 'Copper cathode',
    blurb: 'Grade-A copper. Every winding, busbar and cable in the economy.',
    sector: 'manufacturing',
    tier: 0,
    maturity: 'commodity',
    unit: 'tonne',
    sale: 'unit',
    life: 1,
    // Around $9,800/t on the exchanges through 2026.
    price: 9_800,
    segment: 'enterprise',
    demand: 6_800_000,
    elasticity: 0.9,
    capacity: 'plant',
    draw: 0.6,
    labour: 0.01,
  }),
  node({
    id: 'res_steel_alloy',
    label: 'Structural steel',
    blurb: 'Hot-rolled alloy plate and section. What large things are made of.',
    sector: 'manufacturing',
    tier: 0,
    maturity: 'commodity',
    unit: 'tonne',
    sale: 'unit',
    life: 1,
    price: 850,
    segment: 'enterprise',
    demand: 420_000_000,
    elasticity: 0.7,
    capacity: 'plant',
    draw: 0.09,
    labour: 0.002,
  }),
  node({
    id: 'res_aluminium',
    label: 'Aluminium billet',
    blurb: 'Extrusion-grade billet. Light structure, heat sinks, vehicle bodies.',
    sector: 'manufacturing',
    tier: 0,
    maturity: 'commodity',
    unit: 'tonne',
    sale: 'unit',
    life: 1,
    price: 2_600,
    segment: 'enterprise',
    demand: 18_000_000,
    elasticity: 0.8,
    capacity: 'plant',
    draw: 0.2,
    labour: 0.004,
  }),
  node({
    id: 'res_rare_earth_oxides',
    label: 'Rare earth oxides',
    blurb: 'Neodymium and dysprosium oxide. Small tonnages, enormous leverage.',
    sector: 'manufacturing',
    tier: 0,
    maturity: 'commodity',
    unit: 'kg',
    sale: 'unit',
    life: 1,
    price: 95,
    segment: 'enterprise',
    demand: 42_000_000,
    elasticity: 0.6,
    capacity: 'plant',
    draw: 0.000_2,
    labour: 0.000_02,
  }),
  node({
    // A tier-0 resource rather than a tier-2 material: a fab buys chemicals in
    // and the tier rule forbids a material consuming a material, so the
    // formulation step is folded into the price the fab pays.
    id: 'res_fab_chemicals',
    label: 'Fab chemicals and gases',
    blurb: 'Photoresists, etchants and process gases, priced per wafer set.',
    sector: 'manufacturing',
    tier: 0,
    maturity: 'commodity',
    unit: 'wafer set',
    sale: 'unit',
    life: 1,
    price: 600,
    capacity: 'plant',
    draw: 0.001,
    labour: 0.000_4,
    segment: 'enterprise',
    demand: 9_000_000,
    elasticity: 0.5,
  }),
  node({
    id: 'res_specialty_polymers',
    label: 'Specialty polymers',
    blurb: 'Engineering plastics and films: housings, insulation, packaging stock.',
    sector: 'manufacturing',
    tier: 0,
    maturity: 'commodity',
    unit: 'kg',
    sale: 'unit',
    life: 1,
    price: 3.2,
    segment: 'enterprise',
    demand: 900_000_000,
    elasticity: 1,
    capacity: 'plant',
    draw: 0.000_01,
    labour: 0.000_001,
  }),

  /* --- tier 2: materials ------------------------------------------------ */
  node({
    id: 'mat_wafer_300mm',
    label: '300mm logic wafer',
    blurb: 'A processed advanced-node wafer, out of the fab and ready to dice.',
    sector: 'manufacturing',
    tier: 2,
    maturity: 'established',
    unit: 'wafer',
    sale: 'unit',
    life: 1,
    // 2026 foundry pricing: about $20,000 at 3nm, $18,500 at 5nm, $9,500 at
    // 7nm. $14,000 is the middle of the leading-edge band. A blank polished
    // wafer is $100-200 of that; the rest is the fab, which is the plant draw.
    price: 14_000,
    consumes: [
      ['res_silicon_feedstock', 1.4, true],
      ['res_fab_chemicals', 1, false],
    ],
    capacity: 'plant',
    draw: 0.222, // A $20bn leading-edge fab starts roughly 90,000 wafers a quarter.
    labour: 0.004,
    energy: 1.4, // Leading-edge logic runs about 1.4 MWh per wafer.
    support: 0.03,
    talent: ['hardware_design', 'infrastructure'],
  }),
  node({
    id: 'mat_dram_wafer',
    label: 'DRAM wafer',
    blurb: 'A processed memory wafer. Cheaper node, brutal cyclicality.',
    sector: 'manufacturing',
    tier: 2,
    maturity: 'established',
    unit: 'wafer',
    sale: 'unit',
    life: 1,
    price: 4_500,
    consumes: [
      ['res_silicon_feedstock', 1.4, true],
      ['res_fab_chemicals', 0.7, false],
    ],
    capacity: 'plant',
    draw: 0.06,
    labour: 0.002,
    energy: 0.9,
    support: 0.03,
  }),
  node({
    id: 'mat_cathode_active',
    label: 'Cathode active material',
    blurb: 'NMC or LFP powder. The single largest line in a cell bill of materials.',
    sector: 'manufacturing',
    tier: 2,
    maturity: 'established',
    unit: 'tonne',
    sale: 'unit',
    life: 1,
    price: 21_000,
    consumes: [
      ['res_lithium_carbonate', 0.25, false],
      ['res_nickel_sulphate', 0.35, true],
    ],
    capacity: 'plant',
    draw: 1.2,
    labour: 0.03,
    energy: 8,
    segment: 'enterprise',
    demand: 640_000,
    elasticity: 0.9,
  }),
  node({
    id: 'mat_anode_material',
    label: 'Anode material',
    blurb: 'Coated graphite, increasingly with silicon in it. Charge rate lives here.',
    sector: 'manufacturing',
    tier: 2,
    maturity: 'established',
    unit: 'tonne',
    sale: 'unit',
    life: 1,
    price: 9_000,
    consumes: [['res_graphite', 1.05, false]],
    capacity: 'plant',
    draw: 0.6,
    labour: 0.02,
    energy: 6,
    segment: 'enterprise',
    demand: 380_000,
    elasticity: 0.9,
  }),
  node({
    id: 'mat_electrolyte_separator',
    label: 'Electrolyte and separator',
    blurb: 'The two thin things between the electrodes that decide whether a cell burns.',
    sector: 'manufacturing',
    tier: 2,
    maturity: 'established',
    unit: 'tonne',
    sale: 'unit',
    life: 1,
    price: 14_000,
    consumes: [['res_specialty_polymers', 300, true]],
    capacity: 'plant',
    draw: 0.9,
    labour: 0.02,
    energy: 5,
    segment: 'enterprise',
    demand: 210_000,
    elasticity: 0.8,
  }),
  node({
    id: 'mat_permanent_magnet',
    label: 'Permanent magnets',
    blurb: 'Sintered NdFeB. Every efficient motor and generator turns on these.',
    sector: 'manufacturing',
    tier: 2,
    maturity: 'established',
    unit: 'kg',
    sale: 'unit',
    life: 1,
    price: 75,
    consumes: [['res_rare_earth_oxides', 0.42, false]],
    capacity: 'plant',
    draw: 0.000_6,
    labour: 0.000_08,
    energy: 0.02,
    segment: 'enterprise',
    demand: 62_000_000,
    elasticity: 0.6,
  }),
  node({
    id: 'mat_carbon_composite',
    label: 'Carbon composite',
    blurb: 'Prepreg and laid-up structure. Stiff, light and slow to make.',
    sector: 'manufacturing',
    tier: 2,
    maturity: 'established',
    unit: 'kg',
    sale: 'unit',
    life: 1,
    price: 28,
    consumes: [['res_specialty_polymers', 0.6, true]],
    capacity: 'plant',
    draw: 0.000_9,
    labour: 0.000_3,
    energy: 0.05,
    segment: 'enterprise',
    demand: 42_000_000,
    elasticity: 0.9,
  }),

  /* --- tier 3: components ---------------------------------------------- */
  node({
    id: 'cmp_logic_die',
    label: 'Logic die',
    blurb: 'A mainstream advanced-node die, tested and known good.',
    sector: 'manufacturing',
    tier: 3,
    maturity: 'established',
    unit: 'die',
    sale: 'unit',
    life: 1,
    // About 45 known-good die per $14,000 wafer at mainstream die sizes.
    price: 420,
    consumes: [['mat_wafer_300mm', 0.022, false]],
    capacity: 'plant',
    draw: 0.000_5,
    labour: 0.000_05,
    energy: 0.02,
    segment: 'enterprise',
    demand: 620_000_000,
    elasticity: 0.9,
  }),
  node({
    id: 'cmp_accelerator_die',
    label: 'Accelerator die',
    blurb: 'A reticle-limit compute die. Nine to a wafer if the yield is kind.',
    sector: 'manufacturing',
    tier: 3,
    maturity: 'emerging',
    unit: 'die',
    sale: 'unit',
    life: 1,
    // Nine known-good reticle-limit die per $14,000 wafer is about $1,550 of
    // silicon; $1,900 is that plus test and the yield the fab actually gets.
    price: 1_900,
    requires: ['mat_wafer_300mm'],
    consumes: [['mat_wafer_300mm', 0.1, false]],
    capacity: 'plant',
    draw: 0.004,
    labour: 0.000_3,
    energy: 0.06,
    talent: ['hardware_design', 'infrastructure'],
    segment: 'enterprise',
    demand: 2_400_000,
    elasticity: 0.6,
  }),
  node({
    id: 'cmp_hbm_stack',
    label: 'HBM stack',
    blurb: 'Twelve-high stacked memory. The part of an accelerator that is scarce.',
    sector: 'manufacturing',
    tier: 3,
    maturity: 'emerging',
    unit: 'stack',
    sale: 'unit',
    life: 1,
    // 12-high HBM3E ran about $300 and reached $500 under 2026 shortage;
    // $400 is the middle and the balance price.
    price: 400,
    requires: ['mat_dram_wafer'],
    consumes: [['mat_dram_wafer', 0.05, false]],
    capacity: 'plant',
    draw: 0.001_2,
    labour: 0.000_1,
    energy: 0.03,
    talent: ['hardware_design', 'efficiency'],
    segment: 'enterprise',
    demand: 24_000_000,
    elasticity: 0.5,
  }),
  node({
    id: 'cmp_ic_substrate',
    label: 'IC substrate',
    blurb: 'Build-up film substrate. Unglamorous, and it has been the bottleneck twice.',
    sector: 'manufacturing',
    tier: 3,
    maturity: 'established',
    unit: 'substrate',
    sale: 'unit',
    life: 1,
    price: 95,
    consumes: [
      ['res_specialty_polymers', 0.09, true],
      ['res_copper_cathode', 0.000_6, true],
    ],
    capacity: 'plant',
    draw: 0.000_3,
    labour: 0.000_06,
    energy: 0.01,
    segment: 'enterprise',
    demand: 180_000_000,
    elasticity: 0.8,
  }),
  node({
    id: 'cmp_network_switch_asic',
    label: 'Switch ASIC',
    blurb: 'The fabric silicon that turns seventy-two accelerators into one machine.',
    sector: 'manufacturing',
    tier: 3,
    maturity: 'emerging',
    unit: 'ASIC',
    sale: 'unit',
    life: 1,
    price: 2_400,
    requires: ['mat_wafer_300mm'],
    consumes: [['mat_wafer_300mm', 0.03, false]],
    capacity: 'plant',
    draw: 0.003,
    labour: 0.000_4,
    energy: 0.05,
    talent: ['hardware_design', 'infrastructure'],
    segment: 'enterprise',
    demand: 1_600_000,
    elasticity: 0.6,
  }),
  node({
    id: 'cmp_battery_cell',
    label: 'Battery cell',
    blurb: 'A finished cell, priced by the kilowatt-hour it stores.',
    sector: 'manufacturing',
    tier: 3,
    maturity: 'established',
    unit: 'kWh',
    sale: 'unit',
    life: 1,
    // China cell costs run near $50/kWh and Western near $80; $58 is the
    // global mix behind BloombergNEF's $105/kWh pack average for 2026.
    price: 58,
    consumes: [
      ['mat_cathode_active', 0.001_35, false],
      ['mat_anode_material', 0.000_8, false],
      ['mat_electrolyte_separator', 0.000_45, false],
    ],
    capacity: 'plant',
    draw: 0.000_9,
    labour: 0.000_03,
    energy: 0.04, // Cell manufacture uses roughly 40 kWh per kWh of capacity.
    segment: 'enterprise',
    demand: 620_000_000,
    elasticity: 1,
  }),
  node({
    id: 'mat_machined_structure',
    label: 'Machined structure',
    blurb: 'Precision frames, housings and gearboxes, priced by the kilogram.',
    sector: 'manufacturing',
    tier: 2,
    maturity: 'established',
    unit: 'kg',
    sale: 'unit',
    life: 1,
    price: 34,
    consumes: [
      ['res_aluminium', 0.000_9, true],
      ['res_steel_alloy', 0.000_5, true],
    ],
    capacity: 'plant',
    draw: 0.001_1,
    labour: 0.000_25,
    energy: 0.02,
    segment: 'enterprise',
    demand: 240_000_000,
    elasticity: 0.9,
  }),
  node({
    id: 'cmp_power_electronics',
    label: 'Power electronics',
    blurb: 'Inverters and converters, priced by the kilowatt they can move.',
    sector: 'manufacturing',
    tier: 3,
    maturity: 'established',
    unit: 'kW',
    sale: 'unit',
    life: 1,
    price: 55,
    consumes: [
      ['mat_wafer_300mm', 0.000_9, false],
      ['res_copper_cathode', 0.000_8, true],
      ['res_specialty_polymers', 0.12, true],
    ],
    capacity: 'plant',
    draw: 0.000_5,
    labour: 0.000_07,
    energy: 0.008,
    segment: 'enterprise',
    demand: 92_000_000,
    elasticity: 0.9,
  }),
  node({
    id: 'cmp_electric_drivetrain',
    label: 'Electric drivetrain',
    blurb: 'Motor, reduction and controller as one unit, priced by the kilowatt.',
    sector: 'manufacturing',
    tier: 3,
    maturity: 'established',
    unit: 'kW',
    sale: 'unit',
    life: 1,
    price: 38,
    consumes: [
      ['mat_permanent_magnet', 0.14, false],
      ['res_copper_cathode', 0.001_2, true],
      ['mat_wafer_300mm', 0.000_08, true],
    ],
    capacity: 'plant',
    draw: 0.000_4,
    labour: 0.000_06,
    energy: 0.006,
    segment: 'enterprise',
    demand: 140_000_000,
    elasticity: 0.9,
  }),
  node({
    id: 'cmp_transformer',
    label: 'Power transformer',
    blurb: 'Large grid transformer, priced by MVA. Four-year lead times and rising.',
    sector: 'manufacturing',
    tier: 3,
    maturity: 'established',
    unit: 'MVA',
    sale: 'unit',
    life: 1,
    // Large power transformers ran roughly $30,000-$60,000 per MVA in 2026;
    // $45,000 is the middle, and the lead time is the real scarcity.
    price: 45_000,
    consumes: [
      ['res_copper_cathode', 1.1, false],
      ['res_steel_alloy', 2.4, false],
    ],
    capacity: 'plant',
    draw: 0.9,
    labour: 0.05,
    energy: 3,
    segment: 'enterprise',
    demand: 480_000,
    elasticity: 0.4,
  }),

  /* --- tier 4-6: assembled semiconductors and packs --------------------- */
  node({
    id: 'sys_advanced_package',
    label: 'Advanced package',
    blurb: 'One compute die and its memory stacks on a single interposer.',
    sector: 'manufacturing',
    tier: 4,
    maturity: 'frontier',
    unit: 'package',
    sale: 'unit',
    life: 1,
    // CoWoS-class packaging alone ran $750-$1,100 per chip in 2026; the price
    // here is the finished package, silicon and memory included.
    price: 9_000,
    requires: ['cmp_accelerator_die', 'cmp_hbm_stack'],
    consumes: [
      ['cmp_accelerator_die', 1, false],
      ['cmp_hbm_stack', 8, false],
      ['cmp_ic_substrate', 1, false],
    ],
    capacity: 'plant',
    draw: 0.02,
    labour: 0.001_2,
    energy: 0.09,
    talent: ['hardware_design', 'infrastructure'],
    segment: 'enterprise',
    demand: 2_200_000,
    elasticity: 0.5,
  }),
  node({
    id: 'sys_battery_pack',
    label: 'Battery pack',
    blurb: 'Cells, cooling and a management system, priced by the kilowatt-hour.',
    sector: 'manufacturing',
    tier: 4,
    maturity: 'established',
    unit: 'kWh',
    sale: 'unit',
    life: 32,
    // BloombergNEF: pack prices averaged $108/kWh in 2025 and were forecast to
    // fall about 3% to $105/kWh in 2026.
    price: 105,
    consumes: [
      ['cmp_battery_cell', 1, false],
      ['cmp_power_electronics', 0.1, true],
      ['mat_machined_structure', 0.25, true],
    ],
    capacity: 'plant',
    draw: 0.000_6,
    labour: 0.000_04,
    energy: 0.02,
    segment: 'enterprise',
    demand: 320_000_000,
    elasticity: 1,
  }),
  node({
    id: 'sys_ai_accelerator',
    label: 'AI accelerator',
    blurb: 'One board of frontier compute. The unit every training budget is counted in.',
    sector: 'manufacturing',
    tier: 5,
    maturity: 'frontier',
    unit: 'accelerator',
    sale: 'unit',
    life: 14,
    // Street prices for H200-class parts ran $30,000-$40,000 in 2026 under
    // acute shortage. $20,000 is the balance price: cost plus a fab margin,
    // which is what the market clears at once supply catches up.
    price: 20_000,
    requires: ['sys_advanced_package'],
    consumes: [
      ['sys_advanced_package', 1, false],
      ['cmp_power_electronics', 2, true],
      ['mat_machined_structure', 3, true],
    ],
    capacity: 'plant',
    draw: 0.03,
    labour: 0.002,
    energy: 0.4,
    talent: ['hardware_design', 'infrastructure', 'efficiency'],
    segment: 'enterprise',
    demand: 1_500_000,
    elasticity: 0.5,
    dataYield: 0.000_01,
  }),
  node({
    id: 'sys_ai_server_rack',
    label: 'AI server rack',
    blurb: 'Seventy-two accelerators wired as one machine, delivered on a pallet.',
    sector: 'manufacturing',
    tier: 6,
    maturity: 'frontier',
    unit: 'rack',
    sale: 'unit',
    life: 14,
    // A GB200/GB300 NVL72 rack was quoted at $2.8m-$3.4m through 2026.
    price: 3_000_000,
    requires: ['sys_ai_accelerator'],
    consumes: [
      ['sys_ai_accelerator', 72, false],
      ['cmp_network_switch_asic', 18, false],
      ['cmp_power_electronics', 140, true],
      ['mat_machined_structure', 900, true],
      ['cmp_transformer', 0.15, true],
    ],
    capacity: 'plant',
    draw: 1.4,
    labour: 0.12,
    energy: 12,
    talent: ['infrastructure', 'hardware_design'],
    segment: 'enterprise',
    demand: 4_000,
    elasticity: 0.4,
    dataYield: 0.000_8,
  }),
];

/* -------------------------------------------------------------------------- */
/*  Energy                                                                     */
/* -------------------------------------------------------------------------- */

const ENERGY_NODES: readonly EconomicNode[] = [
  node({
    id: 'res_natural_gas',
    label: 'Natural gas',
    blurb: 'Delivered gas. Still the marginal fuel, so still the marginal price.',
    sector: 'energy',
    tier: 0,
    maturity: 'commodity',
    unit: 'MMBtu',
    sale: 'unit',
    life: 1,
    // Henry Hub was projected to average about $4.00/MMBtu in 2026.
    price: 4,
    segment: 'enterprise',
    demand: 9_400_000_000,
    elasticity: 0.6,
    capacity: 'grid',
    draw: 0.000_02,
    labour: 0.000_001,
  }),
  node({
    id: 'res_uranium_fuel',
    label: 'Uranium fuel',
    blurb: 'Enriched fuel assemblies, priced back to the pound of yellowcake.',
    sector: 'energy',
    tier: 0,
    maturity: 'commodity',
    unit: 'lb U3O8',
    sale: 'unit',
    life: 1,
    price: 82,
    segment: 'enterprise',
    demand: 48_000_000,
    elasticity: 0.3,
    capacity: 'grid',
    draw: 0.001,
    labour: 0.000_05,
  }),
  node({
    id: GRID_POWER_NODE_ID,
    label: 'Grid power',
    blurb: 'A megawatt-hour delivered at the wholesale node. Every other node buys this.',
    sector: 'energy',
    tier: 1,
    maturity: 'commodity',
    unit: 'MWh',
    sale: 'unit',
    life: 1,
    // The EIA's load-weighted average of eleven regional wholesale prices was
    // forecast at $51/MWh for 2026, up from $47 in 2025.
    price: 51,
    consumes: [
      ['res_natural_gas', 6.9, true], // A modern combined-cycle heat rate.
      ['res_uranium_fuel', 0.005, true],
    ],
    capacity: 'grid',
    draw: 0.000_4,
    labour: 0.000_002,
    energy: 0, // INVARIANT: power cannot consume itself.
    segment: 'enterprise',
    demand: 900_000_000,
    elasticity: 0.4,
  }),
  node({
    id: 'mat_solar_module',
    label: 'Solar module',
    blurb: 'A 600-watt panel off the line. The cheapest electron-maker ever built.',
    sector: 'energy',
    tier: 2,
    maturity: 'commodity',
    unit: 'panel',
    sale: 'unit',
    life: 80,
    // About $0.10 per watt in 2026, so roughly $60 for a 600 W module.
    price: 60,
    consumes: [
      ['res_silicon_feedstock', 1.4, false],
      ['res_aluminium', 0.004, true],
      ['res_specialty_polymers', 1.4, true],
    ],
    capacity: 'plant',
    draw: 0.000_4,
    labour: 0.000_05,
    energy: 0.35,
    segment: 'consumer',
    demand: 190_000_000,
    elasticity: 1.4,
  }),
  node({
    id: 'sys_electrolyser_stack',
    label: 'Electrolyser stack',
    blurb: 'The stack that turns cheap power into hydrogen, priced by the megawatt.',
    sector: 'energy',
    tier: 4,
    maturity: 'emerging',
    unit: 'MW',
    sale: 'unit',
    life: 40,
    // A complete electrolyser plant runs $300,000-$500,000 per MW; this is the
    // stack itself, which is roughly a third to a half of that.
    price: 160_000,
    consumes: [
      ['cmp_power_electronics', 1_000, false],
      ['res_rare_earth_oxides', 20, true],
      ['res_steel_alloy', 12, true],
    ],
    capacity: 'plant',
    draw: 1.1,
    labour: 0.09,
    energy: 4,
    talent: ['efficiency', 'infrastructure'],
    segment: 'enterprise',
    demand: 1_800,
    elasticity: 1.1,
  }),
  node({
    id: 'sys_solar_array',
    label: 'Solar array',
    blurb: 'A megawatt of panels, racking and inverters, shipped ready to build.',
    sector: 'energy',
    tier: 4,
    maturity: 'established',
    unit: 'MW',
    sale: 'unit',
    life: 80,
    // Utility solar lands near $0.90-$1.10 per watt installed; $600,000/MW is
    // the equipment, the rest being site construction and the plant draw.
    price: 600_000,
    consumes: [
      ['mat_solar_module', 1_667, false],
      ['cmp_power_electronics', 1_100, false],
      ['cmp_transformer', 1.1, false],
      ['res_steel_alloy', 45, true],
    ],
    capacity: 'grid',
    draw: 0.6,
    labour: 0.14,
    energy: 8,
    segment: 'enterprise',
    demand: 62_000,
    elasticity: 1.2,
  }),
  node({
    id: 'sys_wind_turbine',
    label: 'Wind turbine',
    blurb: 'A six-megawatt machine. Two thousand tonnes of decision, delivered by road.',
    sector: 'energy',
    tier: 4,
    maturity: 'established',
    unit: 'turbine',
    sale: 'unit',
    life: 80,
    // Onshore turbine supply runs roughly $0.9m-$1.1m per MW; $6m is a 6 MW
    // machine at the middle of that band.
    price: 6_000_000,
    consumes: [
      ['mat_carbon_composite', 60_000, false],
      ['cmp_power_electronics', 6_000, false],
      ['mat_permanent_magnet', 2_000, false],
      ['res_steel_alloy', 300, true],
    ],
    capacity: 'plant',
    draw: 5.5,
    labour: 1.1,
    energy: 900,
    segment: 'enterprise',
    demand: 4_800,
    elasticity: 0.8,
  }),
  node({
    id: 'sys_smr_module',
    label: 'SMR module',
    blurb: 'A factory-built reactor module, priced by the megawatt it will carry.',
    sector: 'energy',
    tier: 4,
    maturity: 'frontier',
    unit: 'MW',
    sale: 'unit',
    life: 80,
    // A complete SMR plant runs near $6m/MW overnight; $2.3m/MW is the
    // factory-built module itself, the balance being site construction.
    price: 2_300_000,
    requires: ['cmp_transformer'],
    consumes: [
      ['res_steel_alloy', 700, false],
      ['mat_machined_structure', 8_000, false],
      ['cmp_transformer', 1.2, false],
      ['cmp_power_electronics', 1_100, true],
    ],
    capacity: 'plant',
    draw: 3.2,
    labour: 0.9,
    energy: 260,
    talent: ['infrastructure', 'safety_alignment'],
    segment: 'government',
    demand: 900,
    elasticity: 0.3,
  }),
  node({
    id: 'sys_grid_storage_system',
    label: 'Grid storage system',
    blurb: 'A megawatt-hour of containerised storage, inverter and controls included.',
    sector: 'energy',
    tier: 4,
    maturity: 'established',
    unit: 'MWh',
    sale: 'unit',
    life: 48,
    // Stationary storage packs fell to about $70/kWh in 2025; a delivered
    // system with power conversion and controls lands near $150/kWh.
    price: 150_000,
    consumes: [
      ['cmp_battery_cell', 1_000, false],
      ['cmp_power_electronics', 250, false],
      ['mat_machined_structure', 400, true],
    ],
    capacity: 'grid',
    draw: 0.14,
    labour: 0.03,
    energy: 20,
    segment: 'enterprise',
    demand: 92_000,
    elasticity: 1,
  }),
  node({
    id: 'sys_substation',
    label: 'Substation',
    blurb: 'A megavolt-ampere of switchgear and transformation between two voltages.',
    sector: 'energy',
    tier: 4,
    maturity: 'established',
    unit: 'MVA',
    sale: 'unit',
    life: 80,
    price: 140_000,
    consumes: [
      ['cmp_transformer', 1, false],
      ['res_copper_cathode', 1.5, false],
      ['res_steel_alloy', 8, true],
      ['cmp_power_electronics', 60, true],
    ],
    capacity: 'grid',
    draw: 0.12,
    labour: 0.04,
    energy: 2,
    segment: 'enterprise',
    demand: 220_000,
    elasticity: 0.4,
  }),
  node({
    id: 'svc_hydrogen_supply',
    label: 'Hydrogen supply',
    blurb: 'Electrolytic hydrogen by the tonne. Mostly a very expensive way to store power.',
    sector: 'energy',
    tier: 5,
    maturity: 'emerging',
    unit: 'tonne H2',
    sale: 'unit',
    life: 1,
    price: 4_200,
    requires: ['sys_electrolyser_stack'],
    consumes: [['sys_electrolyser_stack', 0.000_02, false]],
    capacity: 'grid',
    draw: 0.02,
    labour: 0.002,
    energy: 55, // Electrolysis needs roughly 55 MWh per tonne of hydrogen.
    talent: ['efficiency', 'infrastructure'],
    segment: 'enterprise',
    demand: 2_400_000,
    elasticity: 1.3,
  }),
  node({
    id: 'svc_grid_interconnect',
    label: 'Grid interconnection',
    blurb: 'Firm connection rights, per megawatt per quarter. The real queue in this economy.',
    sector: 'energy',
    tier: 5,
    maturity: 'established',
    unit: 'MW-quarter',
    sale: 'contract',
    term: 16,
    price: 9_000,
    requires: ['sys_substation'],
    consumes: [['sys_substation', 0.012, false]],
    capacity: 'grid',
    draw: 0.05,
    labour: 0.004,
    energy: 22,
    segment: 'enterprise',
    demand: 180_000,
    elasticity: 0.3,
  }),
  node({
    id: 'svc_power_purchase_agreement',
    label: 'Power purchase agreement',
    blurb: 'Twenty quarters of firm supply at a fixed price, per megawatt per quarter.',
    sector: 'energy',
    tier: 6,
    maturity: 'established',
    unit: 'MW-quarter',
    sale: 'contract',
    term: 20,
    // One megawatt held for a quarter is about 2,184 MWh; at $51 that is
    // $111,000 of energy, and $118,000 is that plus the firming premium.
    price: 118_000,
    consumes: [['svc_grid_interconnect', 1, false]],
    capacity: 'grid',
    // A generator does not buy this power at the wholesale index and resell it;
    // it builds a plant. The megawatt-quarter is therefore installed capital,
    // roughly $1.2m per megawatt, and energyMwhPerUnit is zero on purpose.
    draw: 1.2,
    labour: 0.002,
    energy: 0,
    segment: 'enterprise',
    demand: 220_000,
    elasticity: 0.5,
  }),
  node({
    id: 'svc_datacentre_capacity',
    label: 'Datacentre capacity',
    blurb: 'A megawatt of IT load, powered and cooled, per quarter. What compute actually sits in.',
    sector: 'energy',
    tier: 6,
    maturity: 'emerging',
    unit: 'MW-quarter',
    sale: 'contract',
    term: 20,
    // Standard facilities cost $10m-$13m per MW to build in 2026 and AI-ready
    // ones $20m-$37m; leased capacity clears near $450,000 per MW-quarter.
    price: 450_000,
    requires: ['svc_grid_interconnect'],
    consumes: [
      ['svc_grid_interconnect', 1, false],
      ['sys_grid_storage_system', 0.03, true],
    ],
    capacity: 'grid',
    draw: 3.6,
    labour: 0.4,
    energy: 2_730, // 2,184 MWh of IT load at a power usage effectiveness of 1.25.
    talent: ['infrastructure', 'efficiency'],
    segment: 'enterprise',
    demand: 62_000,
    elasticity: 0.6,
    dataYield: 0.002,
  }),
  node({
    id: 'svc_grid_balancing',
    label: 'Grid balancing',
    blurb: 'Frequency response and reserve, sold by the megawatt-quarter to the system operator.',
    sector: 'energy',
    tier: 6,
    maturity: 'established',
    unit: 'MW-quarter',
    sale: 'recurring',
    price: 26_000,
    consumes: [['sys_grid_storage_system', 0.02, false]],
    capacity: 'grid',
    draw: 0.09,
    labour: 0.003,
    energy: 90,
    segment: 'government',
    demand: 84_000,
    elasticity: 0.4,
  }),
];

/* -------------------------------------------------------------------------- */
/*  AI                                                                         */
/* -------------------------------------------------------------------------- */

const AI_NODES: readonly EconomicNode[] = [
  node({
    id: 'dat_web_corpus',
    label: 'Curated corpus',
    blurb: 'Cleaned, deduplicated, rights-cleared text and video, priced by the terabyte.',
    sector: 'ai',
    tier: 2,
    maturity: 'established',
    unit: 'TB curated',
    sale: 'unit',
    life: 12,
    price: 18_000,
    capacity: 'none',
    labour: 0.02,
    energy: 0.4,
    talent: ['data_curation', 'retrieval'],
    dataPb: 0.2,
    segment: 'enterprise',
    demand: 42_000,
    elasticity: 1.1,
    dataSensitivity: 0.55,
  }),
  node({
    id: 'dat_preference_data',
    label: 'Preference data',
    blurb: 'Expert-graded comparisons. Ten thousand judgements at a time.',
    sector: 'ai',
    tier: 2,
    maturity: 'established',
    unit: '10k samples',
    sale: 'unit',
    life: 8,
    price: 60_000,
    capacity: 'none',
    labour: 0.9,
    talent: ['evaluation', 'data_curation'],
    dataPb: 0.01,
    segment: 'enterprise',
    demand: 9_000,
    elasticity: 0.9,
    dataSensitivity: 0.4,
  }),
  node({
    id: 'svc_training_run',
    label: 'Training run',
    blurb: 'A block of training compute sold as a service, priced per 10^24 FLOP.',
    sector: 'ai',
    tier: 3,
    maturity: 'emerging',
    unit: '1e24 FLOP',
    sale: 'unit',
    life: 1,
    price: 300_000,
    consumes: [['dat_web_corpus', 0.5, true]],
    capacity: 'compute',
    // 126 accelerators held for one quarter is about 10^24 FLOP of useful work.
    draw: 126,
    labour: 0.02,
    // 126 accelerators at 1.2 kW for 2,184 hours is roughly 330 MWh.
    energy: 330,
    computeIntensity: 1,
    talent: ['training_systems', 'infrastructure'],
    segment: 'developer_api',
    demand: 62_000,
    elasticity: 1.2,
    dataYield: 0.000_2,
  }),
  node({
    id: 'svc_model_evaluation',
    label: 'Model evaluation',
    blurb: 'Independent capability and safety testing, sold per evaluated model.',
    sector: 'ai',
    tier: 3,
    maturity: 'emerging',
    unit: 'evaluation',
    sale: 'unit',
    life: 1,
    price: 140_000,
    consumes: [['dat_preference_data', 1.2, false]],
    capacity: 'compute',
    draw: 4,
    labour: 0.6,
    energy: 11,
    computeIntensity: 0.5,
    talent: ['evaluation', 'safety_alignment'],
    segment: 'enterprise',
    demand: 3_200,
    elasticity: 0.7,
    dataYield: 0.000_4,
  }),
  node({
    id: 'sys_frontier_model',
    label: 'Frontier model',
    blurb: 'A trained and aligned frontier model, licensed for eight quarters at a time.',
    sector: 'ai',
    tier: 4,
    maturity: 'frontier',
    unit: 'licence',
    sale: 'unit',
    life: 8,
    price: 22_000_000,
    requires: ['svc_training_run', 'dat_web_corpus'],
    consumes: [
      ['svc_training_run', 40, false],
      ['dat_web_corpus', 180, false],
      ['dat_preference_data', 15, false],
    ],
    capacity: 'compute',
    draw: 40,
    labour: 12,
    computeIntensity: 1,
    talent: ['reasoning', 'training_systems', 'safety_alignment', 'evaluation'],
    dataPb: 8,
    segment: 'enterprise',
    demand: 90,
    elasticity: 0.6,
    dataYield: 0.02,
    dataSensitivity: 0.5,
  }),
  node({
    id: 'sys_efficient_small_model',
    label: 'Small model',
    blurb: 'A distilled model that fits on one accelerator. Most of the capability, a tenth of the cost.',
    sector: 'ai',
    tier: 4,
    maturity: 'emerging',
    unit: 'licence',
    sale: 'unit',
    life: 8,
    price: 2_400_000,
    requires: ['svc_training_run'],
    consumes: [
      ['svc_training_run', 4, false],
      ['dat_web_corpus', 30, false],
    ],
    capacity: 'compute',
    draw: 6,
    labour: 3,
    computeIntensity: 0.6,
    talent: ['efficiency', 'training_systems'],
    dataPb: 1.5,
    segment: 'developer_api',
    demand: 640,
    elasticity: 1,
    dataYield: 0.004,
    dataSensitivity: 0.35,
  }),
  node({
    id: 'svc_inference_api',
    label: 'Inference API',
    blurb: 'Tokens served on demand, priced per million. The meter the whole industry runs on.',
    sector: 'ai',
    tier: 5,
    maturity: 'established',
    unit: '1M tokens',
    sale: 'unit',
    life: 1,
    // Frontier APIs ran $2.50-$15 per million tokens in and out through 2026;
    // $6.00 is the blended middle.
    price: 6,
    requires: ['sys_frontier_model'],
    consumes: [
      ['sys_frontier_model', 0.000_000_02, true],
      ['sys_efficient_small_model', 0.000_000_15, true],
    ],
    capacity: 'compute',
    // One accelerator serves roughly 30,000 million-token units a quarter.
    draw: 0.000_033_3,
    labour: 0.000_000_2,
    energy: 0.000_09,
    support: 0.05,
    computeIntensity: 0.9,
    talent: ['infrastructure', 'efficiency'],
    segment: 'developer_api',
    demand: 900_000_000,
    elasticity: 1.4,
    dataYield: 0.000_000_1,
    dataSensitivity: 0.6,
  }),
  node({
    id: 'app_agent_platform',
    label: 'Agent platform',
    blurb: 'Tools, memory and orchestration around a model, sold by the seat.',
    sector: 'ai',
    tier: 6,
    maturity: 'emerging',
    unit: 'seat',
    sale: 'recurring',
    price: 2_400,
    requires: ['svc_inference_api'],
    consumes: [['svc_inference_api', 90, false]],
    capacity: 'compute',
    draw: 0.003,
    labour: 0.000_6,
    support: 0.09,
    computeIntensity: 0.7,
    talent: ['agents', 'reasoning', 'security'],
    segment: 'enterprise',
    demand: 14_000_000,
    elasticity: 0.7,
    churn: [0.04, 0.11],
    dataYield: 0.000_002,
    dataSensitivity: 0.7,
  }),
  node({
    id: 'app_ai_software_suite',
    label: 'AI software suite',
    blurb: 'The workaday enterprise application with a model behind every field.',
    sector: 'ai',
    tier: 6,
    maturity: 'established',
    unit: 'seat',
    sale: 'recurring',
    price: 1_500,
    consumes: [['svc_inference_api', 40, true]],
    capacity: 'compute',
    draw: 0.001_2,
    labour: 0.000_5,
    support: 0.1,
    computeIntensity: 0.4,
    talent: ['reasoning', 'retrieval'],
    segment: 'enterprise',
    demand: 46_000_000,
    elasticity: 0.8,
    churn: [0.03, 0.09],
    dataYield: 0.000_001,
    dataSensitivity: 0.65,
  }),
  node({
    id: 'app_vertical_ai_app',
    label: 'Vertical application',
    blurb: 'One industry, one workflow, one model tuned to it. Narrow and sticky.',
    sector: 'ai',
    tier: 6,
    maturity: 'emerging',
    unit: 'seat',
    sale: 'recurring',
    price: 900,
    consumes: [['svc_inference_api', 22, true]],
    capacity: 'compute',
    draw: 0.000_7,
    labour: 0.000_4,
    support: 0.12,
    computeIntensity: 0.35,
    talent: ['retrieval', 'evaluation'],
    segment: 'enterprise',
    demand: 62_000_000,
    elasticity: 0.9,
    churn: [0.04, 0.1],
    dataYield: 0.000_001,
    dataSensitivity: 0.6,
  }),
];

/* -------------------------------------------------------------------------- */
/*  Robotics                                                                   */
/* -------------------------------------------------------------------------- */

const ROBOTICS_NODES: readonly EconomicNode[] = [
  node({
    id: 'dat_robot_telemetry',
    label: 'Robot telemetry',
    blurb: 'Hours of real manipulation and failure, priced by the petabyte. The scarce input.',
    sector: 'robotics',
    tier: 2,
    maturity: 'emerging',
    unit: 'PB',
    sale: 'unit',
    life: 12,
    price: 180_000,
    capacity: 'none',
    labour: 0.4,
    energy: 1.2,
    talent: ['data_curation', 'agents'],
    dataPb: 1,
    segment: 'enterprise',
    demand: 2_600,
    elasticity: 1,
    dataSensitivity: 0.25,
  }),
  node({
    id: 'cmp_precision_actuator',
    label: 'Precision actuator',
    blurb: 'Motor, harmonic drive, encoder and brake as one joint.',
    sector: 'robotics',
    tier: 3,
    maturity: 'established',
    unit: 'actuator',
    sale: 'unit',
    life: 28,
    price: 850,
    consumes: [
      ['mat_permanent_magnet', 0.9, false],
      ['mat_machined_structure', 3.2, false],
      ['mat_wafer_300mm', 0.000_4, true],
    ],
    capacity: 'plant',
    draw: 0.001_4,
    labour: 0.000_2,
    energy: 0.03,
    segment: 'enterprise',
    demand: 12_000_000,
    elasticity: 0.9,
  }),
  node({
    id: 'cmp_sensor_suite',
    label: 'Sensor suite',
    blurb: 'Depth, vision and inertial sensing calibrated as one head.',
    sector: 'robotics',
    tier: 3,
    maturity: 'established',
    unit: 'suite',
    sale: 'unit',
    life: 24,
    price: 1_400,
    consumes: [
      ['mat_wafer_300mm', 0.008, false],
      ['mat_machined_structure', 1.4, true],
      ['res_specialty_polymers', 0.6, true],
    ],
    capacity: 'plant',
    draw: 0.001_1,
    labour: 0.000_2,
    energy: 0.02,
    segment: 'enterprise',
    demand: 6_400_000,
    elasticity: 1,
  }),
  node({
    id: 'sys_edge_compute_module',
    label: 'Edge compute module',
    blurb: 'A rugged inference board that runs a policy on the machine itself.',
    sector: 'robotics',
    tier: 4,
    maturity: 'established',
    unit: 'module',
    sale: 'unit',
    life: 20,
    // Rugged edge inference modules ran roughly $400-$2,000 in 2026.
    price: 850,
    consumes: [
      ['cmp_logic_die', 1, false],
      ['cmp_ic_substrate', 1, false],
      ['res_specialty_polymers', 0.08, true],
    ],
    capacity: 'plant',
    draw: 0.001_6,
    labour: 0.000_25,
    energy: 0.04,
    talent: ['hardware_design', 'efficiency'],
    segment: 'enterprise',
    demand: 9_400_000,
    elasticity: 1,
  }),
  node({
    id: 'sys_robot_policy_model',
    label: 'Robot policy model',
    blurb: 'A manipulation policy trained on real telemetry. The difference between a demo and a shift.',
    sector: 'robotics',
    tier: 4,
    maturity: 'frontier',
    unit: 'licence',
    sale: 'unit',
    life: 12,
    price: 3_200_000,
    requires: ['svc_training_run', 'dat_robot_telemetry'],
    consumes: [
      ['svc_training_run', 6, false],
      ['dat_robot_telemetry', 2, false],
    ],
    capacity: 'compute',
    draw: 8,
    labour: 2.4,
    computeIntensity: 0.9,
    talent: ['agents', 'reasoning', 'training_systems'],
    dataPb: 3,
    segment: 'enterprise',
    demand: 260,
    elasticity: 0.7,
    dataYield: 0.006,
  }),
  node({
    id: 'sys_industrial_arm',
    label: 'Industrial arm',
    blurb: 'Six axes bolted to a floor. Boring, profitable and still the volume market.',
    sector: 'robotics',
    tier: 5,
    maturity: 'established',
    unit: 'arm',
    sale: 'unit',
    life: 40,
    // Six-axis industrial robots ran roughly $25,000-$60,000 in 2026.
    price: 38_000,
    consumes: [
      ['cmp_precision_actuator', 8, false],
      ['cmp_sensor_suite', 1, false],
      ['sys_edge_compute_module', 1, false],
      ['mat_machined_structure', 200, false],
      ['sys_robot_policy_model', 0.000_6, true],
    ],
    capacity: 'plant',
    draw: 0.06,
    labour: 0.012,
    energy: 0.15,
    segment: 'enterprise',
    demand: 160_000,
    elasticity: 0.8,
    dataYield: 0.000_02,
  }),
  node({
    id: 'sys_warehouse_amr',
    label: 'Warehouse AMR',
    blurb: 'A mobile robot that brings the shelf to the picker instead of the other way round.',
    sector: 'robotics',
    tier: 5,
    maturity: 'established',
    unit: 'robot',
    sale: 'unit',
    life: 28,
    // Goods-to-person AMRs ran $25,000-$50,000 per unit in 2026.
    price: 28_000,
    consumes: [
      ['cmp_precision_actuator', 4, false],
      ['cmp_sensor_suite', 2, false],
      ['sys_edge_compute_module', 1, false],
      ['sys_battery_pack', 3, false],
      ['sys_robot_policy_model', 0.001_5, true],
    ],
    capacity: 'plant',
    draw: 0.045,
    labour: 0.009,
    energy: 0.12,
    segment: 'enterprise',
    demand: 90_000,
    elasticity: 1,
    dataYield: 0.000_04,
  }),
  node({
    id: 'sys_humanoid_robot',
    label: 'Humanoid robot',
    blurb: 'Two arms, two legs and twenty-two joints of unresolved argument.',
    sector: 'robotics',
    tier: 5,
    maturity: 'frontier',
    unit: 'robot',
    sale: 'unit',
    life: 20,
    // 2026 street prices spanned $13,500 (Unitree G1) to about $90,000 (H1),
    // with industrial units clustering at $20,000-$45,000. $42,000 is a
    // work-capable machine at the middle of the industrial band.
    price: 42_000,
    requires: ['sys_robot_policy_model'],
    consumes: [
      ['cmp_precision_actuator', 22, false],
      ['cmp_sensor_suite', 2, false],
      ['sys_edge_compute_module', 2, false],
      ['sys_battery_pack', 2, false],
      ['sys_robot_policy_model', 0.002_2, false],
    ],
    capacity: 'plant',
    draw: 0.08,
    labour: 0.03,
    energy: 0.1,
    talent: ['agents', 'hardware_design', 'reasoning'],
    segment: 'enterprise',
    demand: 40_000,
    elasticity: 1.2,
    dataYield: 0.000_2,
    dataSensitivity: 0.3,
  }),
  node({
    id: 'sys_autonomous_drone',
    label: 'Autonomous drone',
    blurb: 'Inspection, survey and increasingly delivery. Cheap enough to lose.',
    sector: 'robotics',
    tier: 5,
    maturity: 'established',
    unit: 'drone',
    sale: 'unit',
    life: 12,
    price: 9_500,
    consumes: [
      ['cmp_electric_drivetrain', 8, false],
      ['cmp_sensor_suite', 2, false],
      ['sys_edge_compute_module', 1, false],
      ['sys_battery_pack', 1.5, false],
      ['sys_robot_policy_model', 0.000_4, true],
    ],
    capacity: 'plant',
    draw: 0.012,
    labour: 0.003,
    energy: 0.03,
    segment: 'enterprise',
    demand: 250_000,
    elasticity: 1.3,
    dataYield: 0.000_03,
    dataSensitivity: 0.4,
  }),
  node({
    id: 'svc_robot_fleet_management',
    label: 'Fleet management',
    blurb: 'Uptime, updates and incident review for somebody else\'s robots, per robot per quarter.',
    sector: 'robotics',
    tier: 6,
    maturity: 'emerging',
    unit: 'robot-quarter',
    sale: 'recurring',
    price: 1_100,
    consumes: [
      ['svc_inference_api', 26, true],
      ['dat_robot_telemetry', 0.000_4, true],
    ],
    capacity: 'compute',
    draw: 0.000_9,
    labour: 0.001_2,
    support: 0.14,
    talent: ['agents', 'infrastructure'],
    segment: 'enterprise',
    demand: 3_400_000,
    elasticity: 0.7,
    churn: [0.03, 0.08],
    dataYield: 0.000_02,
  }),
];

/* -------------------------------------------------------------------------- */
/*  Logistics                                                                  */
/* -------------------------------------------------------------------------- */

const LOGISTICS_NODES: readonly EconomicNode[] = [
  node({
    id: 'res_diesel_fuel',
    label: 'Diesel',
    blurb: 'Still what most of the world\'s freight actually burns.',
    sector: 'logistics',
    tier: 0,
    maturity: 'commodity',
    unit: 'gallon',
    sale: 'unit',
    life: 1,
    price: 3.8,
    segment: 'enterprise',
    demand: 14_000_000_000,
    elasticity: 0.5,
    capacity: 'fleet',
    draw: 0.000_001,
    labour: 0.000_000_2,
  }),
  node({
    id: 'mat_packaging_materials',
    label: 'Packaging',
    blurb: 'Board, film and void fill. Nobody notices it until it costs more than the freight.',
    sector: 'logistics',
    tier: 2,
    maturity: 'commodity',
    unit: 'kg',
    sale: 'unit',
    life: 1,
    price: 1.4,
    consumes: [['res_specialty_polymers', 0.25, true]],
    capacity: 'plant',
    draw: 0.000_004,
    labour: 0.000_002,
    energy: 0.002,
    segment: 'enterprise',
    demand: 4_200_000_000,
    elasticity: 1.1,
  }),
  node({
    id: 'sys_electric_truck',
    label: 'Electric truck',
    blurb: 'A class-eight tractor with a five-hundred-kilowatt-hour pack under the cab.',
    sector: 'logistics',
    tier: 5,
    maturity: 'emerging',
    unit: 'truck',
    sale: 'unit',
    life: 32,
    price: 165_000,
    consumes: [
      ['sys_battery_pack', 500, false],
      ['cmp_electric_drivetrain', 350, false],
      ['res_steel_alloy', 8, false],
      ['cmp_sensor_suite', 1, true],
      ['sys_edge_compute_module', 1, true],
    ],
    capacity: 'plant',
    draw: 0.22,
    labour: 0.06,
    energy: 0.6,
    talent: ['hardware_design', 'efficiency'],
    segment: 'enterprise',
    demand: 62_000,
    elasticity: 1,
    dataYield: 0.000_06,
  }),
  node({
    id: 'sys_delivery_van',
    label: 'Delivery van',
    blurb: 'The last-mile workhorse. Bought a thousand at a time or not at all.',
    sector: 'logistics',
    tier: 5,
    maturity: 'established',
    unit: 'van',
    sale: 'unit',
    life: 28,
    price: 56_000,
    consumes: [
      ['sys_battery_pack', 130, false],
      ['cmp_electric_drivetrain', 150, false],
      ['res_steel_alloy', 2.2, false],
      ['cmp_sensor_suite', 1, true],
      ['sys_edge_compute_module', 1, true],
    ],
    capacity: 'plant',
    draw: 0.09,
    labour: 0.02,
    energy: 0.3,
    segment: 'enterprise',
    demand: 420_000,
    elasticity: 1.1,
    dataYield: 0.000_04,
  }),
  node({
    id: 'sys_warehouse_automation_cell',
    label: 'Automation cell',
    blurb: 'Ten thousand square feet of warehouse, robots and racking, commissioned as one thing.',
    sector: 'logistics',
    tier: 6,
    maturity: 'emerging',
    unit: 'cell',
    sale: 'unit',
    life: 40,
    price: 1_400_000,
    requires: ['sys_warehouse_amr'],
    consumes: [
      ['sys_warehouse_amr', 18, false],
      ['sys_industrial_arm', 4, false],
      ['sys_edge_compute_module', 8, false],
      ['mat_machined_structure', 2_000, false],
    ],
    capacity: 'fleet',
    draw: 1.2,
    labour: 0.3,
    energy: 60,
    talent: ['infrastructure', 'agents'],
    segment: 'enterprise',
    demand: 9_400,
    elasticity: 0.9,
    dataYield: 0.001,
  }),
  node({
    id: 'svc_line_haul',
    label: 'Line haul',
    blurb: 'Long-distance freight, priced per loaded mile. The oldest market in the game.',
    sector: 'logistics',
    tier: 6,
    maturity: 'commodity',
    unit: 'loaded mile',
    sale: 'unit',
    life: 1,
    // 2026 national spot averages: dry van $1.92, flatbed $2.18, reefer $2.28
    // a mile, with contract rates 15-30% above spot.
    price: 2.35,
    consumes: [['sys_electric_truck', 0.000_002, true]],
    capacity: 'fleet',
    draw: 0.000_006,
    labour: 0.000_02,
    energy: 0.002,
    segment: 'enterprise',
    demand: 75_000_000_000,
    elasticity: 1.5,
    dataYield: 0.000_000_02,
  }),
  node({
    id: 'svc_last_mile',
    label: 'Last mile',
    blurb: 'The final delivery. Over half of what shipping actually costs.',
    sector: 'logistics',
    tier: 6,
    maturity: 'established',
    unit: 'parcel',
    sale: 'unit',
    life: 1,
    // Urban deliveries ran near $10 a package in 2026 and rural far higher;
    // last mile was about 53% of total logistics cost.
    price: 10.5,
    consumes: [
      ['sys_delivery_van', 0.000_001_1, true],
      ['sys_autonomous_drone', 0.000_000_6, true],
      ['mat_packaging_materials', 0.35, false],
    ],
    capacity: 'fleet',
    draw: 0.000_012,
    labour: 0.000_06,
    energy: 0.001,
    support: 0.06,
    segment: 'consumer',
    demand: 25_000_000_000,
    elasticity: 1.2,
    dataYield: 0.000_000_05,
    dataSensitivity: 0.5,
  }),
  node({
    id: 'svc_routing_platform',
    label: 'Routing platform',
    blurb: 'Software that decides which vehicle goes where. A percent of fuel is a fortune.',
    sector: 'logistics',
    tier: 6,
    maturity: 'emerging',
    unit: 'vehicle-quarter',
    sale: 'recurring',
    price: 95,
    consumes: [['svc_inference_api', 4, true]],
    capacity: 'compute',
    draw: 0.000_15,
    labour: 0.000_08,
    support: 0.1,
    talent: ['agents', 'infrastructure'],
    segment: 'enterprise',
    demand: 42_000_000,
    elasticity: 0.8,
    churn: [0.03, 0.09],
    dataYield: 0.000_000_6,
  }),
  node({
    id: 'svc_freight_brokerage',
    label: 'Freight brokerage',
    blurb: 'Matching loads to capacity for a margin. Thin, enormous and relentlessly automated.',
    sector: 'logistics',
    tier: 6,
    maturity: 'commodity',
    unit: 'load',
    sale: 'unit',
    life: 1,
    price: 210,
    consumes: [['svc_inference_api', 1.4, true]],
    capacity: 'compute',
    draw: 0.000_02,
    labour: 0.000_9,
    support: 0.08,
    segment: 'enterprise',
    demand: 62_000_000,
    elasticity: 1.6,
    dataYield: 0.000_000_4,
  }),
  node({
    id: 'svc_port_terminal',
    label: 'Port terminal',
    blurb: 'Berth, crane and yard, contracted by the thousand containers a quarter.',
    sector: 'logistics',
    tier: 6,
    maturity: 'established',
    unit: '1k TEU-qtr',
    sale: 'contract',
    term: 20,
    price: 168_000,
    consumes: [
      ['sys_warehouse_amr', 0.04, true],
      ['sys_industrial_arm', 0.02, true],
    ],
    capacity: 'fleet',
    draw: 0.9,
    labour: 0.4,
    energy: 42,
    segment: 'enterprise',
    demand: 240_000,
    elasticity: 0.4,
    dataYield: 0.000_04,
  }),
];

/* -------------------------------------------------------------------------- */
/*  Consumer                                                                   */
/* -------------------------------------------------------------------------- */

const CONSUMER_NODES: readonly EconomicNode[] = [
  node({
    id: 'mat_display_panel',
    label: 'Display panel',
    blurb: 'An OLED panel cut to size. The most expensive thing a phone looks at you with.',
    sector: 'consumer',
    tier: 2,
    maturity: 'established',
    unit: 'panel',
    sale: 'unit',
    life: 1,
    price: 95,
    consumes: [
      ['res_specialty_polymers', 0.06, true],
      ['res_rare_earth_oxides', 0.004, true],
    ],
    capacity: 'plant',
    draw: 0.000_3,
    labour: 0.000_04,
    energy: 0.06,
    segment: 'enterprise',
    demand: 420_000_000,
    elasticity: 1.1,
  }),
  node({
    id: 'dat_consumer_behaviour',
    label: 'Behaviour data',
    blurb: 'What millions of people actually did, priced by the petabyte and watched by regulators.',
    sector: 'consumer',
    tier: 2,
    maturity: 'established',
    unit: 'PB',
    sale: 'unit',
    life: 6,
    price: 240_000,
    capacity: 'none',
    labour: 0.3,
    energy: 1.6,
    talent: ['data_curation', 'retrieval'],
    dataPb: 1,
    segment: 'enterprise',
    demand: 6_200,
    elasticity: 1.2,
    dataSensitivity: 0.95,
  }),
  node({
    id: 'cmp_consumer_soc',
    label: 'Consumer SoC',
    blurb: 'The whole phone on one die, neural engine included.',
    sector: 'consumer',
    tier: 3,
    maturity: 'established',
    unit: 'SoC',
    sale: 'unit',
    life: 1,
    price: 90,
    consumes: [
      ['mat_wafer_300mm', 0.004, false],
      ['res_specialty_polymers', 0.02, true],
    ],
    capacity: 'plant',
    draw: 0.000_2,
    labour: 0.000_02,
    energy: 0.01,
    talent: ['hardware_design', 'efficiency'],
    segment: 'enterprise',
    demand: 340_000_000,
    elasticity: 0.9,
  }),
  node({
    id: 'cmp_camera_module',
    label: 'Camera module',
    blurb: 'Sensor, stack and actuator in a package the size of a fingernail.',
    sector: 'consumer',
    tier: 3,
    maturity: 'commodity',
    unit: 'module',
    sale: 'unit',
    life: 1,
    price: 22,
    consumes: [
      ['mat_wafer_300mm', 0.000_6, false],
      ['res_specialty_polymers', 0.01, true],
    ],
    capacity: 'plant',
    draw: 0.000_05,
    labour: 0.000_01,
    energy: 0.004,
    segment: 'enterprise',
    demand: 1_100_000_000,
    elasticity: 1.3,
  }),
  node({
    id: 'sys_consumer_device',
    label: 'Consumer device',
    blurb: 'The phone-shaped thing. Three hundred million of them a quarter.',
    sector: 'consumer',
    tier: 5,
    maturity: 'established',
    unit: 'device',
    sale: 'unit',
    life: 12,
    price: 380,
    consumes: [
      ['cmp_consumer_soc', 1, false],
      ['mat_display_panel', 1, false],
      ['cmp_camera_module', 1, false],
      ['cmp_battery_cell', 0.018, false],
      ['res_specialty_polymers', 0.15, true],
    ],
    capacity: 'plant',
    draw: 0.000_02,
    labour: 0.000_02,
    energy: 0.03,
    support: 0.05,
    segment: 'consumer',
    demand: 300_000_000,
    elasticity: 1.5,
    dataYield: 0.000_001,
    dataSensitivity: 0.75,
  }),
  node({
    id: 'sys_ai_wearable',
    label: 'AI wearable',
    blurb: 'A camera, a microphone and a model, worn. Nobody agrees whether this works yet.',
    sector: 'consumer',
    tier: 5,
    maturity: 'emerging',
    unit: 'device',
    sale: 'unit',
    life: 8,
    price: 165,
    consumes: [
      ['cmp_consumer_soc', 0.5, false],
      ['cmp_camera_module', 1, false],
      ['mat_display_panel', 0.15, true],
      ['cmp_battery_cell', 0.005, false],
      ['res_specialty_polymers', 0.05, true],
    ],
    capacity: 'plant',
    draw: 0.000_02,
    labour: 0.000_03,
    energy: 0.02,
    support: 0.08,
    talent: ['multimodal', 'efficiency'],
    segment: 'consumer',
    demand: 26_000_000,
    elasticity: 1.9,
    dataYield: 0.000_004,
    dataSensitivity: 0.9,
  }),
  node({
    id: 'app_marketplace',
    label: 'Marketplace',
    blurb: 'Somebody else\'s inventory, your checkout, a take rate per active buyer.',
    sector: 'consumer',
    tier: 6,
    maturity: 'established',
    unit: 'buyer-quarter',
    sale: 'recurring',
    price: 9,
    consumes: [
      ['svc_inference_api', 0.1, true],
      ['dat_consumer_behaviour', 0.000_000_01, true],
    ],
    capacity: 'compute',
    draw: 0.000_002,
    labour: 0.000_003,
    support: 0.16,
    segment: 'consumer',
    demand: 500_000_000,
    elasticity: 1.2,
    churn: [0.08, 0.18],
    dataYield: 0.000_000_2,
    dataSensitivity: 0.8,
  }),
  node({
    id: 'app_streaming_media',
    label: 'Streaming media',
    blurb: 'A library and a recommendation engine, billed monthly and cancelled constantly.',
    sector: 'consumer',
    tier: 6,
    maturity: 'established',
    unit: 'subscriber',
    sale: 'recurring',
    price: 36,
    consumes: [['svc_inference_api', 0.05, true]],
    capacity: 'compute',
    draw: 0.000_001_5,
    labour: 0.000_002,
    support: 0.14,
    segment: 'consumer',
    demand: 420_000_000,
    elasticity: 1.6,
    churn: [0.09, 0.2],
    dataYield: 0.000_000_3,
    dataSensitivity: 0.7,
  }),
  node({
    id: 'app_consumer_subscription',
    label: 'Consumer subscription',
    blurb: 'The small monthly app that a hundred million people forget they pay for.',
    sector: 'consumer',
    tier: 6,
    maturity: 'commodity',
    unit: 'subscriber',
    sale: 'recurring',
    price: 16,
    consumes: [['svc_inference_api', 0.4, true]],
    capacity: 'compute',
    draw: 0.000_004,
    labour: 0.000_002,
    support: 0.12,
    segment: 'consumer',
    demand: 620_000_000,
    elasticity: 1.8,
    churn: [0.1, 0.24],
    dataYield: 0.000_000_2,
    dataSensitivity: 0.65,
  }),
  node({
    id: 'app_social_network',
    label: 'Social network',
    blurb: 'Attention, sold by the active user and regulated by the week.',
    sector: 'consumer',
    tier: 6,
    maturity: 'established',
    unit: 'user-quarter',
    sale: 'recurring',
    price: 4,
    consumes: [
      ['svc_inference_api', 0.05, true],
      ['dat_consumer_behaviour', 0.000_000_005, true],
    ],
    capacity: 'compute',
    draw: 0.000_001_2,
    labour: 0.000_001,
    support: 0.18,
    segment: 'consumer',
    demand: 2_400_000_000,
    elasticity: 2.2,
    churn: [0.06, 0.16],
    dataYield: 0.000_000_6,
    dataSensitivity: 0.92,
  }),
  node({
    id: 'svc_brand_retail',
    label: 'Direct brand',
    blurb: 'Your own product, your own storefront, your own returns problem.',
    sector: 'consumer',
    tier: 6,
    maturity: 'established',
    unit: 'order',
    sale: 'unit',
    life: 1,
    price: 74,
    consumes: [
      ['sys_consumer_device', 0.06, true],
      ['mat_packaging_materials', 0.4, false],
    ],
    capacity: 'fleet',
    draw: 0.000_01,
    labour: 0.000_2,
    support: 0.11,
    segment: 'consumer',
    demand: 1_800_000_000,
    elasticity: 1.7,
    dataYield: 0.000_000_4,
    dataSensitivity: 0.6,
  }),
];

/* -------------------------------------------------------------------------- */
/*  The table                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * Every node in the world-3 economy, in sector order and then tier order
 * within each sector. Ids are stable: appending is safe, renaming is not.
 */
export const ECONOMIC_NODES: readonly EconomicNode[] = [
  ...MANUFACTURING_NODES,
  ...ENERGY_NODES,
  ...AI_NODES,
  ...ROBOTICS_NODES,
  ...LOGISTICS_NODES,
  ...CONSUMER_NODES,
];

/** Lookup by id. Total for a known id; undefined for anything else. */
export const ECONOMIC_NODES_BY_ID: Readonly<Record<string, EconomicNode>> = Object.fromEntries(ECONOMIC_NODES.map((entry) => [entry.id, entry]));

/** One node by id, or undefined. */
export function economicNodeById(id: string): EconomicNode | undefined {
  return ECONOMIC_NODES_BY_ID[id];
}

/** Every node in one sector, in table order. Named to avoid `nodesInSector` in `tech.ts`. */
export function economicNodesInSector(sector: Sector): readonly EconomicNode[] {
  return ECONOMIC_NODES.filter((entry) => entry.sector === sector);
}

/** Every node at one tier, in table order. The map draws one lane per tier. */
export function economicNodesAtTier(tier: NodeTier): readonly EconomicNode[] {
  return ECONOMIC_NODES.filter((entry) => entry.tier === tier);
}

/** Nodes that consume `nodeId` — the reverse edge the canvas draws downstream. */
export function economicNodeConsumers(nodeId: string): readonly EconomicNode[] {
  return ECONOMIC_NODES.filter((entry) => entry.consumes.some((input) => input.nodeId === nodeId));
}

/** The sectors the table covers, for tests that walk it sector by sector. */
export const ECONOMIC_NODE_SECTORS = SECTORS;

/**
 * What one unit of a node costs on the open market this quarter: the node's own
 * balance price moved by the index the market phase stored on the session.
 *
 * The single reader of a node price for the whole game — engine, screens and
 * the Chief of Staff alike — so a price can never be computed two ways. An
 * unknown id answers 0 rather than throwing: a corrupt save must not take a
 * quarter down.
 */
export function nodeMarketPriceUsd(state: NodePricedState, nodeId: string): number {
  const node = ECONOMIC_NODES_BY_ID[nodeId];
  if (node === undefined) return 0;
  return nodePriceUsd(node, nodePriceIndex(state, nodeId));
}
