/**
 * @frontier/simulation — scenario/world2/player.ts
 *
 * The fifteen starting shapes a founder can pick in world version 2: the five
 * AI backgrounds the frozen world already had, plus two for each of the other
 * five sectors.
 *
 * A background changes *only* the shape of the player company — what it sells,
 * what it costs to run, what is on its balance sheet. Identity is fixed: the
 * company id, the founder's character id, the board, the register and the seed
 * round are the same whichever card is chosen, so every relationship, every
 * board seat and every saved reference still resolves.
 *
 * The sector and region come from the setup, not from the background: a
 * warehouse-robotics founder in South Asia pays South Asian salaries and sells
 * into South Asian demand, and the background says nothing about either.
 */

import type { BackgroundId, NewGameSetup, Region } from '@frontier/contracts';
import { defaultBackgroundFor, sectorForBackground } from '@frontier/contracts';
import { DEMO_PLAYER_ID } from '../demo';
import { W2_COMPANIES } from './seeds';
import type { V2CompanySeed, V2ProductSeed } from './seeds';

const M = 1_000_000;

/** The founder's character id. Shared with world 1 so the app's ids never move. */
export const W2_PLAYER_CHARACTER_ID = 'chr_avery_sinclair';
export const W2_PLAYER_BOARD_ID = 'brd_player_ventures';

/**
 * Where a company in each region is headquartered when the player has not been
 * asked. One city per region, so the Office screen always has a place name.
 */
export const REGION_CAPITAL: Readonly<Record<Region, string>> = {
  north_america: 'Harbourgate',
  europe: 'Old Quarter',
  east_asia: 'Meridian Bay',
  south_asia: 'Indus Gate',
  middle_east: 'Al-Khalij',
  latin_america: 'Cordillera',
};

/**
 * Everything a background sets. The remaining `V2CompanySeed` fields are
 * identity or come from the setup, so a background is a pure constant.
 */
type PlayerShape = Pick<
  V2CompanySeed,
  | 'archetype'
  | 'sectorId'
  | 'posture'
  | 'riskTolerance'
  | 'standing'
  | 'capabilityLevel'
  | 'pastPerformance'
  | 'revenue'
  | 'margin'
  | 'growthYoY'
  | 'payroll'
  | 'marketing'
  | 'rd'
  | 'capex'
  | 'interest'
  | 'cash'
  | 'debt'
  | 'deferred'
  | 'backlog'
  | 'ppe'
  | 'goodwill'
  | 'investments'
  | 'receivables'
  | 'payables'
  | 'staff'
  | 'morale'
  | 'attrition'
  | 'compute'
  | 'anchorMethod'
> & {
  readonly product: V2ProductSeed;
  /** Opening valuation floor. A pre-revenue company cannot be priced off sales. */
  readonly anchorFloorUsd: number;
};

/**
 * The fifteen backgrounds. Each opening sheet closes on its own — `buildV2Company`
 * derives equity from assets less liabilities — and each survives a first quarter
 * through the real engine with the invariant gate passing.
 */
export const W2_PLAYER_BACKGROUNDS: Readonly<Record<BackgroundId, PlayerShape>> = {
  /* --- AI: the five the frozen world already had ------------------------- */
  frontier_lab: {
    archetype: 'frontier_lab',
    sectorId: 'frontier_models',
    posture: 'aggressive_growth',
    riskTolerance: 0.83,
    standing: 20,
    capabilityLevel: 0.5,
    pastPerformance: 0,
    revenue: 0,
    margin: 0.55,
    growthYoY: 0,
    payroll: 1.28 * M,
    marketing: 0.06 * M,
    rd: 2.6 * M,
    capex: 0.3 * M,
    interest: 0,
    cash: 15 * M,
    debt: 0,
    deferred: 0,
    backlog: 0,
    ppe: 1.2 * M,
    goodwill: 0,
    investments: 0,
    receivables: 0,
    payables: 0.1 * M,
    staff: [6, 8, 0, 1, 1],
    morale: 84,
    attrition: 0.03,
    compute: [800, 600, 0.4 * M],
    product: { name: 'Frontier Preview', segment: 'developer_api', price: 900, churn: 0, growth: 0, quality: 0.35, intensity: 0.8 },
    anchorMethod: 'technology_option_value',
    anchorFloorUsd: 30 * M,
  },
  enterprise_ai: {
    archetype: 'enterprise_ai',
    sectorId: 'enterprise_software',
    posture: 'aggressive_growth',
    riskTolerance: 0.72,
    standing: 27,
    capabilityLevel: 0.44,
    pastPerformance: 0,
    revenue: 0.32 * M,
    margin: 0.65,
    growthYoY: 0.4,
    payroll: 0.6 * M,
    marketing: 0.05 * M,
    rd: 0.2 * M,
    capex: 0.04 * M,
    interest: 0,
    cash: 4 * M,
    debt: 0,
    deferred: 0.02 * M,
    backlog: 0.18 * M,
    ppe: 0.2 * M,
    goodwill: 0,
    investments: 0,
    receivables: 0.05 * M,
    payables: 0.03 * M,
    staff: [4, 2, 1, 0, 1],
    morale: 88,
    attrition: 0.02,
    compute: [0, 0, 0.15 * M],
    product: { name: 'Ventures Copilot', segment: 'enterprise', price: 200, churn: 0.08, growth: 0.31, quality: 0.52, intensity: 0.29 },
    anchorMethod: 'revenue_multiple',
    anchorFloorUsd: 18 * M,
  },
  consumer_ai: {
    archetype: 'consumer_ai',
    sectorId: 'consumer_ai',
    posture: 'aggressive_growth',
    riskTolerance: 0.74,
    standing: 30,
    capabilityLevel: 0.46,
    pastPerformance: 0,
    revenue: 6 * M,
    margin: 0.42,
    growthYoY: 0.44,
    payroll: 0.78 * M,
    marketing: 1.2 * M,
    rd: 0.6 * M,
    capex: 0.05 * M,
    interest: 0,
    cash: 5 * M,
    debt: 0,
    deferred: 0.1 * M,
    backlog: 0.05 * M,
    ppe: 0.3 * M,
    goodwill: 0,
    investments: 0,
    receivables: 0.4 * M,
    payables: 0.5 * M,
    staff: [8, 1, 0, 2, 1],
    morale: 80,
    attrition: 0.06,
    compute: [0, 0, 1 * M],
    product: { name: 'Everyday Copilot', segment: 'consumer', price: 8, churn: 0.16, growth: 0.22, quality: 0.5, intensity: 0.55 },
    anchorMethod: 'revenue_multiple',
    anchorFloorUsd: 22 * M,
  },
  infrastructure: {
    archetype: 'infrastructure',
    sectorId: 'cloud_infrastructure',
    posture: 'balanced',
    riskTolerance: 0.5,
    standing: 34,
    capabilityLevel: 0.5,
    pastPerformance: 20,
    revenue: 12.48 * M,
    margin: 0.4,
    growthYoY: 0.24,
    payroll: 1.25 * M,
    marketing: 0.2 * M,
    rd: 0.4 * M,
    capex: 1 * M,
    interest: 0.16 * M,
    cash: 6 * M,
    debt: 8 * M,
    deferred: 0.3 * M,
    backlog: 2 * M,
    ppe: 18 * M,
    goodwill: 0,
    investments: 0,
    receivables: 0.6 * M,
    payables: 1.2 * M,
    staff: [10, 1, 2, 6, 1],
    morale: 78,
    attrition: 0.03,
    compute: [4_000, 0, 0],
    product: { name: 'Ventures Capacity', segment: 'enterprise', price: 4_800, churn: 0.03, growth: 0.06, quality: 0.62, intensity: 0.9 },
    anchorMethod: 'asset_cashflow_utilisation',
    anchorFloorUsd: 40 * M,
  },
  bootstrapper: {
    archetype: 'enterprise_ai',
    sectorId: 'enterprise_software',
    posture: 'balanced',
    riskTolerance: 0.6,
    standing: 20,
    capabilityLevel: 0.38,
    pastPerformance: 0,
    revenue: 0.162 * M,
    margin: 0.6,
    growthYoY: 0.32,
    payroll: 0.22 * M,
    marketing: 0.02 * M,
    rd: 0.08 * M,
    capex: 0.01 * M,
    interest: 0,
    cash: 1.2 * M,
    debt: 0,
    deferred: 0.01 * M,
    backlog: 0.05 * M,
    ppe: 0.05 * M,
    goodwill: 0,
    investments: 0,
    receivables: 0.03 * M,
    payables: 0.04 * M,
    staff: [2, 0, 1, 0, 1],
    morale: 82,
    attrition: 0.04,
    compute: [0, 0, 0.05 * M],
    product: { name: 'Copilot Lite', segment: 'enterprise', price: 180, churn: 0.1, growth: 0.2, quality: 0.45, intensity: 0.3 },
    anchorMethod: 'revenue_multiple',
    anchorFloorUsd: 6 * M,
  },

  /* --- Robotics ---------------------------------------------------------- */
  warehouse_robotics: {
    archetype: 'enterprise_ai',
    sectorId: 'enterprise_software',
    posture: 'balanced',
    riskTolerance: 0.56,
    standing: 26,
    capabilityLevel: 0.44,
    pastPerformance: 0,
    revenue: 2 * M,
    margin: 0.4,
    growthYoY: 0.3,
    payroll: 0.66 * M,
    marketing: 0.12 * M,
    rd: 0.44 * M,
    capex: 0.5 * M,
    interest: 0.04 * M,
    cash: 7 * M,
    debt: 2 * M,
    deferred: 0.2 * M,
    backlog: 3.4 * M,
    ppe: 4.2 * M,
    goodwill: 0,
    investments: 0,
    receivables: 0.9 * M,
    payables: 0.6 * M,
    staff: [7, 2, 2, 4, 1],
    morale: 79,
    attrition: 0.05,
    compute: [120, 0, 0.2 * M],
    // 1,200 units on service contracts at $1,667 a quarter.
    product: { name: 'Ventures Pick Fleet', segment: 'enterprise', price: 1_667, churn: 0.05, growth: 0.12, quality: 0.55, intensity: 0.42 },
    anchorMethod: 'revenue_multiple',
    anchorFloorUsd: 20 * M,
  },
  humanoid_lab: {
    archetype: 'frontier_lab',
    sectorId: 'enterprise_software',
    posture: 'research_first',
    riskTolerance: 0.88,
    standing: 22,
    capabilityLevel: 0.4,
    pastPerformance: 0,
    revenue: 0,
    margin: 0.4,
    growthYoY: 0,
    payroll: 1.9 * M,
    marketing: 0.08 * M,
    rd: 2.2 * M,
    capex: 0.9 * M,
    interest: 0,
    cash: 22 * M,
    debt: 0,
    deferred: 0,
    backlog: 0,
    ppe: 4 * M,
    goodwill: 0,
    investments: 0,
    receivables: 0,
    payables: 0.3 * M,
    staff: [9, 11, 0, 3, 1],
    morale: 86,
    attrition: 0.03,
    compute: [600, 900, 0.5 * M],
    product: { name: 'Ventures General Platform', segment: 'enterprise', price: 24_000, churn: 0, growth: 0, quality: 0.3, intensity: 0.72 },
    anchorMethod: 'technology_option_value',
    anchorFloorUsd: 45 * M,
  },

  /* --- Manufacturing ----------------------------------------------------- */
  contract_manufacturer: {
    archetype: 'chip_maker',
    sectorId: 'semiconductors',
    posture: 'efficiency',
    riskTolerance: 0.42,
    standing: 28,
    capabilityLevel: 0.46,
    pastPerformance: 12,
    revenue: 14 * M,
    margin: 0.22,
    growthYoY: 0.12,
    payroll: 1.4 * M,
    marketing: 0.16 * M,
    rd: 0.3 * M,
    capex: 1.6 * M,
    interest: 0.36 * M,
    cash: 9 * M,
    debt: 18 * M,
    deferred: 0.4 * M,
    backlog: 22 * M,
    ppe: 32 * M,
    goodwill: 0,
    investments: 0,
    receivables: 6 * M,
    payables: 7 * M,
    staff: [9, 1, 3, 22, 1],
    morale: 71,
    attrition: 0.05,
    compute: [0, 0, 0.08 * M],
    product: { name: 'Ventures Build Programmes', segment: 'enterprise', price: 46_000, churn: 0.04, growth: 0.05, quality: 0.6, intensity: 0.2 },
    anchorMethod: 'earnings_fcf',
    anchorFloorUsd: 26 * M,
  },
  precision_components: {
    archetype: 'chip_maker',
    sectorId: 'semiconductors',
    posture: 'balanced',
    riskTolerance: 0.46,
    standing: 25,
    capabilityLevel: 0.52,
    pastPerformance: 6,
    revenue: 3 * M,
    margin: 0.36,
    growthYoY: 0.16,
    payroll: 0.62 * M,
    marketing: 0.04 * M,
    rd: 0.26 * M,
    capex: 0.4 * M,
    interest: 0.06 * M,
    cash: 5 * M,
    debt: 3 * M,
    deferred: 0.08 * M,
    backlog: 6 * M,
    ppe: 7 * M,
    goodwill: 0,
    investments: 0,
    receivables: 1.2 * M,
    payables: 0.9 * M,
    staff: [5, 2, 1, 8, 1],
    morale: 80,
    attrition: 0.03,
    compute: [0, 0, 0.04 * M],
    product: { name: 'Ventures Tolerance Parts', segment: 'enterprise', price: 12_000, churn: 0.02, growth: 0.06, quality: 0.72, intensity: 0.16 },
    anchorMethod: 'earnings_fcf',
    anchorFloorUsd: 12 * M,
  },

  /* --- Energy ------------------------------------------------------------ */
  grid_developer: {
    archetype: 'infrastructure',
    sectorId: 'energy_infrastructure',
    posture: 'aggressive_growth',
    riskTolerance: 0.68,
    standing: 24,
    capabilityLevel: 0.44,
    pastPerformance: 8,
    revenue: 2.4 * M,
    margin: 0.36,
    growthYoY: 0.4,
    payroll: 0.7 * M,
    marketing: 0.06 * M,
    rd: 0.14 * M,
    capex: 3.2 * M,
    interest: 0.5 * M,
    cash: 12 * M,
    debt: 25 * M,
    deferred: 0.6 * M,
    backlog: 60 * M,
    ppe: 44 * M,
    goodwill: 0,
    investments: 0,
    receivables: 2 * M,
    payables: 5 * M,
    staff: [6, 1, 3, 9, 1],
    morale: 77,
    attrition: 0.04,
    compute: [0, 0, 0.05 * M],
    product: { name: 'Ventures Connection Programmes', segment: 'enterprise', price: 300_000, churn: 0.01, growth: 0.1, quality: 0.54, intensity: 0.1 },
    anchorMethod: 'asset_cashflow_utilisation',
    anchorFloorUsd: 34 * M,
  },
  renewables_operator: {
    archetype: 'infrastructure',
    sectorId: 'energy_infrastructure',
    posture: 'balanced',
    riskTolerance: 0.4,
    standing: 26,
    capabilityLevel: 0.48,
    pastPerformance: 14,
    revenue: 6 * M,
    margin: 0.44,
    growthYoY: 0.12,
    payroll: 0.5 * M,
    marketing: 0.04 * M,
    rd: 0.08 * M,
    capex: 2.4 * M,
    interest: 0.8 * M,
    cash: 8 * M,
    debt: 40 * M,
    deferred: 0.4 * M,
    backlog: 34 * M,
    ppe: 62 * M,
    goodwill: 0,
    investments: 0,
    receivables: 2.4 * M,
    payables: 4 * M,
    staff: [4, 1, 2, 11, 1],
    morale: 76,
    attrition: 0.03,
    compute: [0, 0, 0.03 * M],
    product: { name: 'Ventures Contracted Generation', segment: 'enterprise', price: 24_000, churn: 0.01, growth: 0.04, quality: 0.66, intensity: 0.08 },
    anchorMethod: 'asset_cashflow_utilisation',
    anchorFloorUsd: 30 * M,
  },

  /* --- Logistics --------------------------------------------------------- */
  freight_network: {
    archetype: 'infrastructure',
    sectorId: 'data_services',
    posture: 'efficiency',
    riskTolerance: 0.38,
    standing: 24,
    capabilityLevel: 0.42,
    pastPerformance: 10,
    revenue: 11 * M,
    margin: 0.18,
    growthYoY: 0.08,
    payroll: 1.5 * M,
    marketing: 0.2 * M,
    rd: 0.12 * M,
    capex: 1.2 * M,
    interest: 0.3 * M,
    cash: 6 * M,
    debt: 15 * M,
    deferred: 0.3 * M,
    backlog: 9 * M,
    ppe: 26 * M,
    goodwill: 0,
    investments: 0,
    receivables: 5 * M,
    payables: 6 * M,
    staff: [6, 0, 5, 48, 1],
    morale: 66,
    attrition: 0.08,
    compute: [0, 0, 0.06 * M],
    product: { name: 'Ventures Line Haul', segment: 'enterprise', price: 34_000, churn: 0.06, growth: 0.03, quality: 0.52, intensity: 0.18 },
    anchorMethod: 'earnings_fcf',
    anchorFloorUsd: 16 * M,
  },
  last_mile: {
    archetype: 'consumer_ai',
    sectorId: 'data_services',
    posture: 'land_grab',
    riskTolerance: 0.76,
    standing: 22,
    capabilityLevel: 0.4,
    pastPerformance: 0,
    revenue: 3.2 * M,
    margin: 0.15,
    growthYoY: 0.58,
    payroll: 0.9 * M,
    marketing: 0.8 * M,
    rd: 0.16 * M,
    capex: 0.3 * M,
    interest: 0.04 * M,
    cash: 4 * M,
    debt: 2 * M,
    deferred: 0.1 * M,
    backlog: 1.2 * M,
    ppe: 3.4 * M,
    goodwill: 0,
    investments: 0,
    receivables: 1.1 * M,
    payables: 1.6 * M,
    staff: [5, 0, 4, 36, 1],
    morale: 74,
    attrition: 0.11,
    compute: [0, 0, 0.09 * M],
    product: { name: 'Ventures Same-Day', segment: 'consumer', price: 32, churn: 0.17, growth: 0.24, quality: 0.48, intensity: 0.26 },
    anchorMethod: 'revenue_multiple',
    anchorFloorUsd: 10 * M,
  },

  /* --- Consumer ---------------------------------------------------------- */
  direct_brand: {
    archetype: 'consumer_ai',
    sectorId: 'consumer_ai',
    posture: 'aggressive_growth',
    riskTolerance: 0.7,
    standing: 28,
    capabilityLevel: 0.42,
    pastPerformance: 0,
    revenue: 4 * M,
    margin: 0.52,
    growthYoY: 0.42,
    payroll: 0.56 * M,
    marketing: 1.4 * M,
    rd: 0.2 * M,
    capex: 0.08 * M,
    interest: 0,
    cash: 5 * M,
    debt: 0.5 * M,
    deferred: 0.16 * M,
    backlog: 0.3 * M,
    ppe: 1.4 * M,
    goodwill: 0,
    investments: 0,
    receivables: 1 * M,
    payables: 1.4 * M,
    staff: [5, 1, 4, 6, 1],
    morale: 81,
    attrition: 0.07,
    compute: [0, 0, 0.12 * M],
    product: { name: 'Ventures Direct', segment: 'consumer', price: 26, churn: 0.12, growth: 0.18, quality: 0.56, intensity: 0.34 },
    anchorMethod: 'revenue_multiple',
    anchorFloorUsd: 18 * M,
  },
  retail_platform: {
    archetype: 'consumer_ai',
    sectorId: 'consumer_ai',
    posture: 'land_grab',
    riskTolerance: 0.72,
    standing: 30,
    capabilityLevel: 0.46,
    pastPerformance: 0,
    revenue: 2.6 * M,
    margin: 0.58,
    growthYoY: 0.5,
    payroll: 0.9 * M,
    marketing: 1 * M,
    rd: 0.44 * M,
    capex: 0.06 * M,
    interest: 0,
    cash: 10 * M,
    debt: 0,
    deferred: 0.2 * M,
    backlog: 0.2 * M,
    ppe: 0.8 * M,
    goodwill: 0,
    investments: 0,
    receivables: 0.8 * M,
    payables: 1.1 * M,
    staff: [9, 1, 3, 5, 1],
    morale: 83,
    attrition: 0.06,
    compute: [0, 0, 0.2 * M],
    // 3,400 sellers paying a 12% take on their quarter, averaging $765 of fees.
    product: { name: 'Ventures Marketplace', segment: 'consumer', price: 765, churn: 0.09, growth: 0.21, quality: 0.58, intensity: 0.3 },
    anchorMethod: 'revenue_multiple',
    anchorFloorUsd: 24 * M,
  },
};

/**
 * The background a setup resolves to. A background whose sector disagrees with
 * the chosen sector is not an error: the founder picked a sector first and the
 * card second, so the sector wins and the first card in it is used.
 */
export function backgroundIdFor(setup: NewGameSetup): BackgroundId {
  const declared = setup.backgroundId;
  return sectorForBackground(declared) === setup.sector ? declared : defaultBackgroundFor(setup.sector);
}

/** The player company's seed, from the setup and the background it names. */
export function playerSeedFor(setup: NewGameSetup): V2CompanySeed {
  const shape = W2_PLAYER_BACKGROUNDS[backgroundIdFor(setup)];
  return {
    id: W2_COMPANIES.player,
    slug: 'player_ventures',
    name: setup.companyName,
    ticker: null,
    archetype: shape.archetype,
    tier: 'major',
    sector: setup.sector,
    region: setup.region,
    sectorId: shape.sectorId,
    city: REGION_CAPITAL[setup.region],
    isPublic: false,
    listPriceUsd: null,
    beta: 1.3,
    ceoCharacterId: W2_PLAYER_CHARACTER_ID,
    boardId: W2_PLAYER_BOARD_ID,
    posture: shape.posture,
    riskTolerance: shape.riskTolerance,
    standing: shape.standing,
    capabilityLevel: shape.capabilityLevel,
    pastPerformance: shape.pastPerformance,
    revenue: shape.revenue,
    margin: shape.margin,
    growthYoY: shape.growthYoY,
    payroll: shape.payroll,
    marketing: shape.marketing,
    rd: shape.rd,
    capex: shape.capex,
    interest: shape.interest,
    cash: shape.cash,
    debt: shape.debt,
    deferred: shape.deferred,
    backlog: shape.backlog,
    ppe: shape.ppe,
    goodwill: shape.goodwill,
    investments: shape.investments,
    receivables: shape.receivables,
    payables: shape.payables,
    staff: shape.staff,
    morale: shape.morale,
    attrition: shape.attrition,
    compute: shape.compute,
    product: shape.product,
    anchorMethod: shape.anchorMethod,
    controllerPlayerId: DEMO_PLAYER_ID,
    anchorFloorUsd: shape.anchorFloorUsd,
  };
}
