import { beforeEach, describe, expect, it, vi } from 'vitest';
import { createSession, PLAYER_ID } from '@/lib/game/engine';

const mocks = vi.hoisted(() => ({ calls: [] as any[], submit: vi.fn(), append: vi.fn(), turn: vi.fn(), load: vi.fn(), continuationText: 'I have queued the request for review; it is not approved yet.' }));
vi.mock('../_gateway', () => ({
  admit: async () => ({ ok: true, admission: { principal: { id: PLAYER_ID }, conversationKey: () => 'company-session', finish: (response: Response) => response } }),
  parseBody: async (request: Request, schema: any) => ({ ok: true, value: schema.parse(await request.json()) }),
  runRole: async (call: any) => { const value = await call(); return Response.json(value); },
  gateway: () => ({ roles: { companyDialogue: { converse: async (context: any) => { mocks.calls.push(context); return mocks.calls.length === 1
    ? { output: { text: 'I sign it.', commands: [{ type: 'submit_board_proposal', kind: 'annual_plan', title: 'Plan', summary: 'Approve plan.', amountUsd: null, targetCompanyId: null, stockComponentPct: null }], relationshipDeltas: { trust: 0, respect: 0, hostility: 0 }, newCommitment: null, memoryToStore: null }, fallbackUsed: false }
    : { output: { text: mocks.continuationText, commands: [{ type: 'reject_deal', dealId: 'should_not_execute', reason: 'ignored' }], relationshipDeltas: { trust: 0, respect: 0, hostility: 0 }, newCommitment: null, memoryToStore: null }, fallbackUsed: false }; } } } }),
}));
vi.mock('@/lib/game/server/sessionAuthority', () => ({
  canonicalDialogueTurn: (...args: any[]) => mocks.turn(...args), loadCanonicalCompanyDialogue: (...args: any[]) => mocks.load(...args), submitCompanyCommand: (...args: any[]) => mocks.submit(...args), appendCanonicalDialogueTurn: (...args: any[]) => mocks.append(...args),
}));
const { POST } = await import('./route');
const setup = { companyName: 'Buyer Labs', founderName: 'Avery', backgroundId: 'consumer_ai' as const, sector: 'ai' as const, region: 'north_america' as const, worldVersion: 3 as const };
function request(message = 'Make the offer') { return new Request('http://local/api', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ sessionId: 'session_123', companyId: 'npc_company', turnId: 'turn_12345', message }) }); }
beforeEach(() => { mocks.calls.length = 0; mocks.continuationText = 'I have queued the request for review; it is not approved yet.'; mocks.turn.mockReset().mockReturnValue({ status: 'missing' }); mocks.submit.mockReset().mockResolvedValue({ status: 'queued', revision: 5, queuedAction: { intent: { type: 'submit_board_proposal', kind: 'annual_plan', title: 'Plan', summary: 'Approve plan.', amountUsd: null, targetCompanyId: null, stockComponentPct: null } }, validation: null }); mocks.append.mockReset().mockResolvedValue(6); const state = createSession({ seed: 8123, setup }); const npc = state.companies.find((company) => company.controllerPlayerId === null)!; Object.assign(npc, { id: 'npc_company' }); mocks.load.mockReturnValue({ state, revision: 4, queuedActions: [] }); });
describe('company dialogue receipt continuation', () => {
  it('shows the persisted receipt to pass two, executes no pass-two command, and avoids claiming signature', async () => { const response = await POST(request()); const body = await response.json(); expect(mocks.submit).toHaveBeenCalledTimes(1); expect(JSON.stringify(mocks.calls[1]!.gameFacts)).toContain('PERSISTED RECEIPT'); expect(body.output.text).toContain('not approved'); expect(body.output.commands).toEqual([]); expect(mocks.append.mock.calls[0]![0].receipts[0].status).toBe('queued'); });
  it('returns a stored turn without another model call or command and rejects changed text', async () => { mocks.turn.mockReturnValue({ status: 'complete', playerText: 'Make the offer', replyText: 'Still queued.', receipts: [], fallbackUsed: false, revision: 8 }); const replay = await POST(request()); expect((await replay.json()).output.text).toBe('Still queued.'); expect(mocks.calls).toHaveLength(0); expect(mocks.submit).not.toHaveBeenCalled(); mocks.turn.mockReturnValue({ status: 'conflict' }); expect((await POST(request('changed'))).status).toBe(409); });
  it('cannot present a rejected command as signed even if continuation wording does', async () => { mocks.continuationText = 'I have signed and accepted the agreement.'; mocks.submit.mockResolvedValue({ status: 'rejected', revision: 5, queuedAction: null, validation: { status: 'rejected', reasons: ['board authority required'] } }); const response = await POST(request()); const body = await response.json(); expect(body.receipts[0].status).toBe('rejected'); expect(body.output.text).toContain('no agreement was signed'); expect(body.output.text).not.toBe('I sign it.'); expect(mocks.submit).toHaveBeenCalledTimes(1); });
});
