-- ===========================================================================
-- 0010_people.sql — Frontier Capital
--
-- The people layer. Conversations emerge from actual state, not generic
-- personas: a character has stable traits, current beliefs, a directional
-- relationship with every actor they know and durable memories of what was
-- done to them.
--
-- Two separate concepts, deliberately:
--   * connection_scores — how socially/institutionally powerful someone is.
--   * relationships     — how one particular actor feels about another.
-- Access is gated by the connection GAP; feeling is gated by relationships.
-- ===========================================================================

create type public.character_archetype as enum (
  'founder',
  'chief_executive',
  'executive',
  'researcher',
  'investor',
  'director',
  'regulator',
  'politician',
  'journalist',
  'analyst',
  'employee',
  'lobbyist',
  'academic'
);

create type public.character_status as enum ('active', 'inactive', 'retired', 'deceased');

create type public.trait_kind as enum ('stable', 'belief', 'skill', 'preference');

create type public.memory_kind as enum (
  'interaction',
  'observation',
  'betrayal',
  'favour',
  'deal',
  'public_event',
  'rumour'
);

-- ---------------------------------------------------------------------------
-- characters
-- ---------------------------------------------------------------------------

create table public.characters (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.game_sessions (id) on delete cascade,
  full_name text not null,
  short_name text,
  archetype public.character_archetype not null,
  title text,
  company_id uuid references public.companies (id) on delete set null,
  agency_id uuid references public.agencies (id) on delete set null,
  organisation_label text,
  bio text,
  -- true when this character is the in-world body of a session seat.
  is_player_character boolean not null default false,
  player_id uuid references public.session_players (id) on delete set null,
  -- NPC characters are always visibly labelled as AI-driven in the UI.
  is_npc boolean not null default true,
  connection_level numeric not null default 20,
  public_reputation numeric not null default 0.5,
  media_influence numeric not null default 0.1,
  personal_wealth_usd numeric not null default 0,
  status public.character_status not null default 'active',
  avatar_hint text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint characters_full_name_len check (char_length(full_name) between 1 and 120),
  constraint characters_connection_range check (connection_level between 0 and 100),
  constraint characters_reputation_range check (public_reputation between 0 and 1),
  constraint characters_media_influence_range check (media_influence between 0 and 1),
  constraint characters_wealth_nonneg check (personal_wealth_usd >= 0),
  constraint characters_player_character_consistency
    check (is_player_character = (not is_npc))
);

comment on table public.characters is
  'Every important person: founders, CEOs, investors, directors, regulators, journalists, researchers. NPC characters are LLM-driven and are always labelled as AI in the interface.';
comment on column public.characters.connection_level is
  'How socially and institutionally powerful this person is (0-100). Computed by the engine from reputation, company significance, wealth, board positions, investor relationships, government credibility, media influence and prior exits — never from follower count alone.';
comment on column public.characters.is_npc is
  'AI-driven. Every message from an is_npc character is labelled as generated by an AI character.';

create index characters_session_idx on public.characters (session_id);
create index characters_company_idx on public.characters (company_id);
create index characters_agency_idx on public.characters (agency_id);
create index characters_player_idx on public.characters (player_id);
create index characters_session_archetype_idx on public.characters (session_id, archetype);

create trigger characters_set_updated_at
  before update on public.characters
  for each row execute function public.set_updated_at();

alter table public.characters enable row level security;

-- Deferred foreign keys from earlier migrations.
alter table public.session_players
  add constraint session_players_character_id_fkey
  foreign key (character_id) references public.characters (id) on delete set null;

alter table public.executives
  add constraint executives_character_id_fkey
  foreign key (character_id) references public.characters (id) on delete cascade;

alter table public.board_seats
  add constraint board_seats_character_id_fkey
  foreign key (character_id) references public.characters (id) on delete set null;

alter table public.holdings
  add constraint holdings_holder_character_id_fkey
  foreign key (holder_character_id) references public.characters (id) on delete set null;

alter table public.commitments
  add constraint commitments_actor_character_id_fkey
  foreign key (actor_character_id) references public.characters (id) on delete set null;

alter table public.commitments
  add constraint commitments_beneficiary_character_id_fkey
  foreign key (beneficiary_character_id) references public.characters (id) on delete set null;

alter table public.public_disclosures
  add constraint public_disclosures_issued_by_character_id_fkey
  foreign key (issued_by_character_id) references public.characters (id) on delete set null;

-- ---------------------------------------------------------------------------
-- character_traits
-- ---------------------------------------------------------------------------

create table public.character_traits (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.game_sessions (id) on delete cascade,
  character_id uuid not null references public.characters (id) on delete cascade,
  trait_key text not null,
  kind public.trait_kind not null default 'stable',
  value numeric not null,
  -- Stable dispositions are hidden; a few reputational traits are common knowledge.
  is_public boolean not null default false,
  updated_quarter integer,
  created_at timestamptz not null default now(),
  constraint character_traits_key_format check (trait_key ~ '^[a-z0-9_]{2,48}$'),
  constraint character_traits_value_range check (value between 0 and 100),
  constraint character_traits_unique unique (character_id, trait_key)
);

comment on table public.character_traits is
  'Stable dispositions (risk tolerance, technical orientation, financial conservatism, aggressiveness, status sensitivity) and current beliefs. Hidden by default: knowing exactly how a rival CEO is wired would remove the reason to talk to them.';

create index character_traits_character_idx on public.character_traits (character_id);
create index character_traits_session_idx on public.character_traits (session_id);

alter table public.character_traits enable row level security;

-- ---------------------------------------------------------------------------
-- relationships
-- ---------------------------------------------------------------------------

create table public.relationships (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.game_sessions (id) on delete cascade,
  from_character_id uuid not null references public.characters (id) on delete cascade,
  to_character_id uuid not null references public.characters (id) on delete cascade,
  trust numeric not null default 50,
  respect numeric not null default 50,
  hostility numeric not null default 0,
  dependence numeric not null default 0,
  familiarity numeric not null default 0,
  -- Temporary or permanent access override: shared board, shared investor,
  -- consortium, introduction, conference, acquisition talks, legal proceeding.
  access_override text,
  access_override_until_quarter integer,
  last_interaction_quarter integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint relationships_no_self check (from_character_id <> to_character_id),
  constraint relationships_scores_range check (
    trust between 0 and 100
    and respect between 0 and 100
    and hostility between 0 and 100
    and dependence between 0 and 100
    and familiarity between 0 and 100
  ),
  constraint relationships_access_override_values check (
    access_override is null
    or access_override in (
      'shared_board', 'shared_investor', 'consortium', 'introduction',
      'conference', 'acquisition_talks', 'legal_proceeding', 'media', 'system'
    )
  ),
  constraint relationships_unique unique (session_id, from_character_id, to_character_id)
);

comment on table public.relationships is
  'Directional feelings. A respects B while B despises A is a normal, important state. Access overrides recorded here are how a low-status founder engineers a route to someone far above their connection level.';

create index relationships_from_idx on public.relationships (from_character_id);
create index relationships_to_idx on public.relationships (to_character_id);

create trigger relationships_set_updated_at
  before update on public.relationships
  for each row execute function public.set_updated_at();

alter table public.relationships enable row level security;

-- ---------------------------------------------------------------------------
-- memories
-- ---------------------------------------------------------------------------

create table public.memories (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.game_sessions (id) on delete cascade,
  character_id uuid not null references public.characters (id) on delete cascade,
  quarter integer not null,
  kind public.memory_kind not null default 'interaction',
  subject_character_id uuid references public.characters (id) on delete set null,
  subject_company_id uuid references public.companies (id) on delete set null,
  subject_player_id uuid references public.session_players (id) on delete set null,
  summary text not null,
  sentiment numeric not null default 0,
  salience numeric not null default 0.5,
  decay_rate numeric not null default 0.1,
  -- FK added in 0014_simulation.sql (sim_events).
  source_event_id uuid,
  visibility public.visibility_scope not null default 'private',
  created_at timestamptz not null default now(),
  constraint memories_quarter_positive check (quarter >= 1),
  constraint memories_summary_len check (char_length(summary) between 1 and 400),
  constraint memories_sentiment_range check (sentiment between -1 and 1),
  constraint memories_salience_range check (salience between 0 and 1),
  constraint memories_decay_range check (decay_rate between 0 and 1)
);

comment on table public.memories is
  'What a character remembers and how strongly. "Player poached two researchers" and "Player supported us in a regulatory hearing" are what a dialogue agent is given, so its behaviour is grounded in the ledger rather than invented.';

create index memories_character_idx on public.memories (character_id, quarter desc);
create index memories_subject_character_idx on public.memories (subject_character_id);
create index memories_session_quarter_idx on public.memories (session_id, quarter desc);

alter table public.memories enable row level security;

-- ---------------------------------------------------------------------------
-- connection_scores
-- ---------------------------------------------------------------------------

create table public.connection_scores (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.game_sessions (id) on delete cascade,
  character_id uuid not null references public.characters (id) on delete cascade,
  player_id uuid references public.session_players (id) on delete set null,
  quarter integer not null,
  score numeric not null default 20,
  components jsonb not null default '{}'::jsonb,
  rank integer,
  created_at timestamptz not null default now(),
  constraint connection_scores_quarter_positive check (quarter >= 1),
  constraint connection_scores_score_range check (score between 0 and 100),
  constraint connection_scores_rank_positive check (rank is null or rank >= 1),
  constraint connection_scores_unique unique (session_id, character_id, quarter)
);

comment on table public.connection_scores is
  'Per-quarter Connection Level history. Access rule: if |Connection_A - Connection_B| <= 10 either party may initiate; otherwise only the higher-connection actor may initiate downward, unless an access override exists. Public by design — it is the rule everyone plays against.';
comment on column public.connection_scores.components is
  'Contributions to the score: founder reputation, company significance, personal wealth, board positions, investor relationships, government credibility, media influence, prior exits, public following, high-quality mutual relationships.';

create index connection_scores_session_quarter_idx
  on public.connection_scores (session_id, quarter desc);
create index connection_scores_character_idx on public.connection_scores (character_id, quarter desc);

alter table public.connection_scores enable row level security;
