/**
 * Navigation configuration — data, not markup.
 *
 * Four primary rooms, and one persistent planning action. Each room is one scrolling page; every
 * drill-down is a sheet over it, addressed by `?sheet=` and registered in
 * `lib/sheets.ts`. There is no sub-tab strip, no hamburger and no group: the
 * bottom bar is the whole navigation, so a thumb is never more than one tap
 * from any subject in the game.
 *
 * Screen agents do not edit this file. Adding a *subject* means adding a sheet
 * to `SHEETS`; adding a tab is a decision about the shape of the game.
 */

import type { IconName } from '../components/ui/icons';
import { LEGACY_ROUTES, firstSegmentOf, tabPath, type TabId } from './sheets';

export type { TabId };

export interface Tab {
  readonly id: TabId;
  /** Route path, e.g. `/home`. */
  readonly href: string;
  readonly label: string;
  /** One or two words for compact navigation, where `label` would be too long. */
  readonly short: string;
  /** The flat mark drawn everywhere this tab is offered. */
  readonly icon: IconName;
  /** One line describing the tab; used as a tooltip and on the landing page. */
  readonly blurb: string;
}

export const TABS: readonly Tab[] = [
  {
    id: 'home',
    href: tabPath('home'),
    label: 'Today',
    short: 'Today',
    icon: 'gauge',
    blurb: 'Your company at a glance: cash, revenue, runway, and what needs deciding.',
  },
  {
    id: 'company',
    href: tabPath('company'),
    label: 'Build',
    short: 'Build',
    icon: 'building',
    blurb: 'What you operate: the floor, the lines, the people, research, government, the books.',
  },
  {
    id: 'market',
    href: tabPath('market'),
    label: 'Power',
    short: 'Power',
    icon: 'chart',
    blurb: 'Your stock, your funding, your register, the tape, deals and the board.',
  },
  {
    id: 'world',
    href: tabPath('world'),
    label: 'World',
    short: 'World',
    icon: 'globe',
    blurb: 'The paper, the social feed, the people you know, the standings and the economy.',
  },
] as const;

/** The founder's persistent action. It is intentionally outside the subject navigation. */
export const PLAN_ACTION: Tab = {
  id: 'play',
  href: tabPath('play'),
  label: 'Plan quarter',
  short: 'Plan',
  icon: 'playMark',
  blurb: 'Review your instructions and move the quarter forward.',
};

/** The screen a session lands on. */
export const HOME_ROUTE = tabPath('home');

/** The room or Plan page a pathname is on, or null outside the game. */
export function tabFor(pathname: string): Tab | null {
  return [...TABS, PLAN_ACTION].find((tab) => pathname === tab.href || pathname.startsWith(`${tab.href}/`)) ?? null;
}

/**
 * True when the shell chrome (rail + status bar) should render for this path.
 *
 * An old address is included: `[...legacy]` renders inside the shell for the
 * one frame it takes to `router.replace` onto the new one, and a bare page
 * flashing between the two would be worse than the redirect it is hiding.
 */
export function isGamePath(pathname: string): boolean {
  return tabFor(pathname) !== null || Object.prototype.hasOwnProperty.call(LEGACY_ROUTES, firstSegmentOf(pathname));
}
