/**
 * Navigation configuration — data, not markup.
 *
 * The twenty screens of the game, grouped the way a founder thinks about
 * them: what you operate, where the frontier is, how capital moves, what the
 * world is saying, and the controls that end a quarter.
 *
 * The grouping is load-bearing on a phone, where the five groups *are* the
 * bottom tab bar and a group's items are the sub-tabs under the header. Each
 * group therefore has a primary screen — its first item — and that is where
 * tapping the tab lands.
 *
 * Screen agents do not edit this file. Adding a screen means adding a route
 * folder under `src/app/(game)` and an entry here.
 */

import type { IconName } from '../components/ui/icons';

export type NavGroupId = 'operate' | 'frontier' | 'capital' | 'world' | 'play';

export interface NavItem {
  /** Route path, e.g. `/command-centre`. */
  readonly href: string;
  /** Label in the rail. */
  readonly label: string;
  /** The flat mark drawn everywhere this screen is offered. */
  readonly icon: IconName;
  /**
   * The old two-letter monogram.
   *
   * Kept so nothing that still reads the field breaks, but **nothing renders
   * it any more**: every surface draws `icon` instead.
   *
   * @deprecated Use `icon`.
   */
  readonly glyph: string;
  /** One line describing the screen; used as a tooltip and on the landing page. */
  readonly blurb: string;
}

export interface NavGroup {
  readonly id: NavGroupId;
  readonly label: string;
  /** The mark for the group itself: the phone's bottom tab. */
  readonly icon: IconName;
  /** Two or three words for the tab, where `label` would be too long. */
  readonly short: string;
  readonly items: readonly NavItem[];
}

export const NAV_GROUPS: readonly NavGroup[] = [
  {
    id: 'operate',
    label: 'Operate',
    icon: 'desk',
    short: 'Operate',
    items: [
      { href: '/command-centre', label: 'Command Centre', icon: 'gauge', glyph: 'CC', blurb: 'Quarter summary, cash, runway, valuation, alerts.' },
      { href: '/company', label: 'Company', icon: 'building', glyph: 'CO', blurb: 'Operating structure, subsidiaries, offices, reputation.' },
      { href: '/products', label: 'Products', icon: 'box', glyph: 'PR', blurb: 'Products, pricing, customers, unit economics.' },
      // The whole-economy overlay: the six-sector chain and its prices, the
      // market-share ladder, the regional freight tolls. One tap from home,
      // because every price on Financials is now a consequence of it.
      { href: '/sector', label: 'Sector', icon: 'globe', glyph: 'SE', blurb: 'The six-sector chain, goods prices, market share and freight tolls.' },
      { href: '/people', label: 'People', icon: 'people', glyph: 'PE', blurb: 'Employees, executives, culture, compensation.' },
      { href: '/financials', label: 'Financials', icon: 'ledger', glyph: 'FI', blurb: 'P&L, balance sheet, cash flow, segment results.' },
    ],
  },
  {
    id: 'frontier',
    label: 'Frontier',
    icon: 'compass',
    short: 'Frontier',
    items: [
      { href: '/research', label: 'Research', icon: 'flask', glyph: 'RE', blurb: 'The generative technology graph and research programmes.' },
      { href: '/government', label: 'Government', icon: 'capitol', glyph: 'GO', blurb: 'Opportunities, bids, active contracts, compliance.' },
      { href: '/deal-room', label: 'Deal Room', icon: 'handshake', glyph: 'DR', blurb: 'M&A, licensing, partnerships, negotiations.' },
    ],
  },
  {
    id: 'capital',
    label: 'Capital',
    icon: 'vault',
    short: 'Capital',
    items: [
      { href: '/markets', label: 'Markets', icon: 'chart', glyph: 'MK', blurb: 'In-world exchange, ownership, reference tape.' },
      { href: '/capital', label: 'Capital', icon: 'coins', glyph: 'CA', blurb: 'Funding, debt, treasury, cap table, runway.' },
      // The institutions: venture, buyout, hedge and sovereign capital as
      // actors with cash, a clock and a thesis. It sits beside Markets and
      // Capital because it is the other side of both — who is on your register
      // and what they can still spend on you.
      { href: '/street', label: 'The Street', icon: 'briefcase', glyph: 'ST', blurb: 'Funds, their dry powder, their offers and their short books.' },
      { href: '/boardroom', label: 'Boardroom', icon: 'boardTable', glyph: 'BR', blurb: 'Agenda, directors, votes, governance.' },
    ],
  },
  {
    id: 'world',
    label: 'World',
    icon: 'globe',
    short: 'World',
    items: [
      // One feed, not a dashboard: the screen is the public record, and the map
      // is a tab on it. Named the way the Command Centre already links to it.
      { href: '/news', label: 'News', icon: 'newspaper', glyph: 'WO', blurb: 'The universal public record, and the living map.' },
      { href: '/social', label: 'Social', icon: 'chat', glyph: 'SO', blurb: 'Synthetic social networks, PR, marketing.' },
      { href: '/network', label: 'Network', icon: 'network', glyph: 'NE', blurb: 'Investors, founders, officials, directors, journalists.' },
      { href: '/leaderboard', label: 'Leaderboard', icon: 'trophy', glyph: 'LB', blurb: 'Session rankings and the power network.' },
    ],
  },
  {
    id: 'play',
    label: 'Play',
    icon: 'playMark',
    short: 'Play',
    items: [
      { href: '/chief-of-staff', label: 'Chief of Staff', icon: 'briefcase', glyph: 'CS', blurb: 'Conversational control interface: interpret, propose, confirm.' },
      { href: '/end-quarter', label: 'End Quarter', icon: 'stamp', glyph: 'EQ', blurb: 'Review queued actions and lock the submission.' },
      { href: '/quarter-resolution', label: 'Quarter Resolution', icon: 'newspaper', glyph: 'QR', blurb: 'Exactly what changed last quarter, and why.' },
    ],
  },
] as const;

/** Every screen, flattened, in rail order. */
export const NAV_ITEMS: readonly NavItem[] = NAV_GROUPS.flatMap((group) => group.items);

/** Routes that render inside the game shell. */
export const GAME_ROUTES: readonly string[] = NAV_ITEMS.map((item) => item.href);

/** The screen a session lands on. */
export const HOME_ROUTE = '/command-centre';

/** True when this pathname is that screen, or a route beneath it. */
function matches(pathname: string, href: string): boolean {
  return pathname === href || pathname.startsWith(`${href}/`);
}

/** Look a screen up by pathname; returns null for the landing and auth pages. */
export function navItemFor(pathname: string): NavItem | null {
  return NAV_ITEMS.find((item) => matches(pathname, item.href)) ?? null;
}

/** The group a pathname belongs to, or null. */
export function navGroupFor(pathname: string): NavGroup | null {
  return NAV_GROUPS.find((group) => group.items.some((item) => matches(pathname, item.href))) ?? null;
}

/**
 * The screen a group's tab lands on: its first item.
 *
 * The phone's bottom bar navigates to groups, not screens, so this is the one
 * place that decides what "Capital" means when you tap it.
 */
export function primaryHrefOf(group: NavGroup): string {
  return group.items[0]?.href ?? HOME_ROUTE;
}

/**
 * The sibling screens shown as sub-tabs under the header on a phone.
 *
 * Empty for a group with a single screen — a strip of one tab is noise — and
 * empty off a game route.
 */
export function navSiblingsFor(pathname: string): readonly NavItem[] {
  const group = navGroupFor(pathname);
  if (group === null || group.items.length < 2) return [];
  return group.items;
}

/** True when the shell chrome (rail + status bar) should render for this path. */
export function isGamePath(pathname: string): boolean {
  return navItemFor(pathname) !== null;
}
